/*
 * Web pages - AUTO-GENERATED from the plain HTML files in the www dir.
 * Do not edit by hand: edit the html files there, then run
 *     python tools/pages.py build
 */
#ifndef GW_PAGES_H
#define GW_PAGES_H

static const char PAGE_WIFI[] =
"<!doctype html>\n"
"<html lang=\"ru\">\n"
"\n"
"<head>\n"
"    <meta charset=\"utf-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"    <title>SKE-02 Gateway - Wi-Fi</title>\n"
"    <style>\n"
"        body {\n"
"            font: 13px/1.45 system-ui, sans-serif;\n"
"            background: #14171c;\n"
"            color: #d8dee9;\n"
"            max-width: 520px;\n"
"            margin: auto;\n"
"            padding: 0 12px\n"
"        }\n"
"\n"
"        h1 {\n"
"            font-size: 18px\n"
"        }\n"
"\n"
"        label {\n"
"            display: block;\n"
"            margin: 12px 0 4px;\n"
"            color: #8b94a7\n"
"        }\n"
"\n"
"        input {\n"
"            width: 100%;\n"
"            box-sizing: border-box;\n"
"            background: #0e1116;\n"
"            color: #d8dee9;\n"
"            border: 1px solid #39414f;\n"
"            border-radius: 4px;\n"
"            padding: 8px\n"
"        }\n"
"\n"
"        button {\n"
"            margin-top: 14px;\n"
"            background: #2a5bdb;\n"
"            color: #fff;\n"
"            border: 0;\n"
"            border-radius: 4px;\n"
"            padding: 9px 9px;\n"
"            cursor: pointer;\n"
"            font-size: 12px\n"
"        }\n"
"\n"
"        table {\n"
"            width: 100%;\n"
"            border-collapse: collapse;\n"
"            margin-top: 6px\n"
"        }\n"
"\n"
"        td {\n"
"            padding: 6px 8px;\n"
"            border-top: 1px solid #2a3140\n"
"        }\n"
"\n"
"        .pick {\n"
"            background: #233047;\n"
"            color: #d8dee9;\n"
"            border: 1px solid #39414f;\n"
"            border-radius: 6px;\n"
"            padding: 3px 10px;\n"
"            cursor: pointer\n"
"        }\n"
"\n"
"        .dbm {\n"
"            color: #8b94a7\n"
"        }\n"
"    </style>\n"
"</head>\n"
"\n"
"<body>\n"
"    <h1>Настройка Wi-Fi шлюза SKE-02</h1>\n"
"    <form method=\"POST\" action=\"/save\">\n"
"        <label>SSID сети</label><input name=\"ssid\" id=\"ssid\" maxlength=\"32\" autocapitalize=\"off\" autocorrect=\"off\"\n"
"            spellcheck=\"false\" required>\n"
"        <label>Пароль (для открытой сети оставьте пустым)</label><input name=\"pass\" type=\"password\" maxlength=\"64\"\n"
"            autocapitalize=\"off\" autocorrect=\"off\">\n"
"        <button type=\"submit\">Подключиться</button>\n"
"    </form>\n"
"    <h3>Найденные сети</h3>\n"
"    <div id=\"nets\">сканирование…</div>\n"
"    <script>\n"
"        let NETS = [];\n"
"        const esc = s => String(s).replace(/[&<>\"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;' }[c]));\n"
"        async function load(restart) {\n"
"            if (restart) await fetch('/scan?restart=1');\n"
"            const r = await (await fetch('/scan')).json();\n"
"            if (r.running) { setTimeout(() => load(0), 1500); return }\n"
"            NETS = r.nets;\n"
"            let h = '<table>';\n"
"            NETS.forEach((n, i) => {\n"
"                h += '<tr><td>' + esc(n.s) + '</td><td class=\"dbm\">' + n.r + ' dBm</td><td>' +\n"
"                    (n.e ? '🔒' : '') + '</td><td><button class=\"pick\" onclick=\"pick(' + i + ')\">выбрать</button></td></tr>';\n"
"            });\n"
"            document.getElementById('nets').innerHTML = h + '</table>';\n"
"        }\n"
"        function pick(i) { document.getElementById('ssid').value = NETS[i].s }\n"
"        load(1);\n"
"    </script>\n"
"</body>\n"
"\n"
"</html>\n";

static const char PAGE_INDEX[] =
"<!doctype html>\n"
"<html lang=\"ru\">\n"
"\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <title>SKE-02 Gateway</title>\n"
"  <style>\n"
"    body {\n"
"      font: 13px/1.45 system-ui, sans-serif;\n"
"      background: #14171c;\n"
"      color: #d8dee9;\n"
"      margin: 0;\n"
"      padding: 12px\n"
"    }\n"
"\n"
"    header {\n"
"      display: flex;\n"
"      flex-wrap: wrap;\n"
"      gap: 8px;\n"
"      align-items: center;\n"
"      margin-bottom: 10px\n"
"    }\n"
"\n"
"    h1 {\n"
"      font-size: 18px;\n"
"      margin: 0 8px 0 0\n"
"    }\n"
"\n"
"    .tag {\n"
"      background: #2a3140;\n"
"      border-radius: 4px;\n"
"      padding: 2px 8px;\n"
"      font-size: 12px;\n"
"      white-space: nowrap\n"
"    }\n"
"\n"
"    .ok {\n"
"      background: #1d5c2f\n"
"    }\n"
"\n"
"    .bad {\n"
"      background: #6c2431\n"
"    }\n"
"\n"
"    button {\n"
"      background: #2a5bdb;\n"
"      color: #fff;\n"
"      border: 0;\n"
"      border-radius: 4px;\n"
"      padding: 5px 5px;\n"
"      cursor: pointer;\n"
"      font-size: 12px\n"
"    }\n"
"\n"
"    button.warn {\n"
"      background: #a23b2e\n"
"    }\n"
"\n"
"    #debug {\n"
"      display: flex;\n"
"      flex-wrap: wrap;\n"
"      gap: 6px;\n"
"      align-items: center;\n"
"      margin: 0 0 8px 0;\n"
"      padding: 4px 8px;\n"
"      border: 1px dashed #39414f;\n"
"      border-radius: 4px;\n"
"      color: #8b94a7;\n"
"      font-size: 12px\n"
"    }\n"
"\n"
"    #debug .tag {\n"
"      background: transparent;\n"
"      border: 1px solid #2a3140;\n"
"      padding: 1px 6px\n"
"    }\n"
"\n"
"    #debug button {\n"
"      font-size: 12px;\n"
"      padding: 4px 4px\n"
"    }\n"
"\n"
"    #values {\n"
"      display: grid;\n"
"      /* 10 chars of 15px monospace (~90px) + card padding + border */\n"
"      grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));\n"
"      gap: 6px;\n"
"      margin: 0 0 10px 0\n"
"    }\n"
"\n"
"    .vcard {\n"
"      background: #1b202a;\n"
"      border: 2px solid #2a3140;\n"
"      border-radius: 4px;\n"
"      padding: 2px 4px   /* vertical horizontal */\n"
"    }\n"
"\n"
"    .vname {\n"
"      color: #8b94a7;\n"
"      font-size: 11px\n"
"    }\n"
"\n"
"    .vval {\n"
"      font-family: ui-monospace, Consolas, monospace;\n"
"      font-size: 16px;\n"
"      white-space: nowrap\n"
"    }\n"
"\n"
"    .vcard.wide {\n"
"      grid-column: span 2\n"
"    }\n"
"\n"
"    .vcard.chart {\n"
"      grid-column: 1/-1\n"
"    }\n"
"\n"
"    .vcard.chart canvas {\n"
"      width: 100%;\n"
"      height: 120px;\n"
"      display: block\n"
"    }\n"
"\n"
"    .bit {\n"
"      display: inline-block;\n"
"      font-size: 10px;\n"
"      padding: 1px 7px;\n"
"      border-radius: 9px;\n"
"      margin: 1px;\n"
"      background: #232a38;\n"
"      color: #565f6e\n"
"    }\n"
"\n"
"    .bit.on {\n"
"      background: #1d5c2f;\n"
"      color: #d8dee9\n"
"    }\n"
"\n"
"    #btnEdit.act {\n"
"      background: #1d5c2f\n"
"    }\n"
"\n"
"    body.edit .vcard {\n"
"      outline: 1px dashed #39414f;\n"
"      cursor: grab\n"
"    }\n"
"\n"
"    body.edit .vcard.dragging {\n"
"      opacity: .35;\n"
"      cursor: grabbing\n"
"    }\n"
"\n"
"    body.edit #values {\n"
"      user-select: none\n"
"    }\n"
"\n"
"    #btnW.act {\n"
"      background: #1d5c2f\n"
"    }\n"
"\n"
"    #wpanel {\n"
"      background: #1b202a;\n"
"      border: 1px solid #2a3140;\n"
"      border-radius: 4px;\n"
"      padding: 10px 12px;\n"
"      margin: 0 0 10px 0;\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      gap: 6px\n"
"    }\n"
"\n"
"    #wpanel[hidden] {\n"
"      display: none\n"
"    }\n"
"\n"
"    #wpanel .wrow {\n"
"      display: flex;\n"
"      flex-wrap: wrap;\n"
"      gap: 6px;\n"
"      align-items: center;\n"
"      font-size: 13px\n"
"    }\n"
"\n"
"    #wpanel input[type=number] {\n"
"      width: 80px\n"
"    }\n"
"\n"
"    .hbar {\n"
"      background: #0e1116;\n"
"      border: 1px solid #39414f;\n"
"      border-radius: 2px;\n"
"      height: 14px;\n"
"      margin-top: 6px;\n"
"      overflow: hidden\n"
"    }\n"
"\n"
"    /* torn stripe fill: solid dashes with gaps */\n"
"    .hfill {\n"
"      height: 100%;\n"
"      width: 0;\n"
"      transition: width .25s ease-out;\n"
"      /* green torn stripe: wide dashes, hairline gaps */\n"
"      background: repeating-linear-gradient(90deg, #3fbf5f 0 10px, transparent 10px 11px)\n"
"    }\n"
"\n"
"    /* bar card: label + the stripe, 3px horizontal padding */\n"
"    .vcard.wbar {\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      gap: 2px;\n"
"      padding: 3px\n"
"    }\n"
"\n"
"    .vcard.wbar .hbar {\n"
"      height: 16px;\n"
"      margin-top: 0\n"
"    }\n"
"\n"
"    /* percent readout, right-aligned in the bar label line */\n"
"    .bpct {\n"
"      float: right;\n"
"      color: #8b94a7;\n"
"      font-size: 12px;\n"
"      font-family: ui-monospace, Consolas, monospace\n"
"    }\n"
"\n"
"    /* bit-state card: label wraps on spaces, lamp = the active color */\n"
"    .vcard.wbit {\n"
"      display: flex;\n"
"      flex-direction: column;\n"
"      gap: 2px;\n"
"      padding: 3px 5px\n"
"    }\n"
"\n"
"    .vcard.wbit .vname {\n"
"      white-space: normal\n"
"    }\n"
"\n"
"    .bitlamp {\n"
"      height: 16px;\n"
"      border: 1px solid #39414f;\n"
"      border-radius: 6px;\n"
"      background: #0e1116;\n"
"      transition: background .15s\n"
"    }\n"
"\n"
"    .bitlamp.on {\n"
"      box-shadow: 0 0 6px 0 currentColor\n"
"    }\n"
"  </style>\n"
"</head>\n"
"\n"
"<body>\n"
"  <header>\n"
"    <h1>SKE-02 Gateway</h1>\n"
"    <span id=\"link\" class=\"tag\">…</span><span id=\"fw\" class=\"tag\"></span>\n"
"    <button id=\"btnEdit\" onclick=\"toggleEdit()\">&#9998; Раскладка</button>\n"
"    <button id=\"btnW\" onclick=\"toggleW()\">&#9633; Виджеты</button>\n"
"    <a href=\"/settings\"><button>&#9881; Настройки</button></a>\n"
"    <button class=\"warn\" onclick=\"rebootDev()\">Перезагрузить прибор</button>\n"
"    <a href=\"/wifi\"><button>Wi-Fi</button></a>\n"
"  </header>\n"
"  <div id=\"wpanel\" hidden>\n"
"    <div id=\"wlist\"></div>\n"
"  </div>\n"
"  <div id=\"values\"></div>\n"
"  <div id=\"debug\">\n"
"    отладочная панель\n"
"    <button onclick=\"rescan()\">Пересканировать</button>\n"
"    <span class=\"tag\" id=\"ip\"></span><span class=\"tag\" id=\"rss\"></span>\n"
"    <span class=\"tag\" id=\"upt\"></span><span class=\"tag\" id=\"heap\"></span>\n"
"  </div>\n"
"  <script>\n"
"    const $ = i => document.getElementById(i);\n"
"    function hms(t) { const s = t % 60, m = (t / 60 | 0) % 60, h = t / 3600 | 0; return h ? h + 'ч ' + m + 'м' : m ? m + 'м ' + s + 'с' : s + 'с' }\n"
"    /* live values window: MeterData_t fields, names as the struct members;\n"
"     * bitwise members render as FSETPOINT_/FSTATUS_/FISR_ flag chips */\n"
"    const FLAGS = {\n"
"      setpoint: ['RATEQMAX', 'RATEHIGH', 'RATELOW', 'FLOW', 'TOTAL', 'GTOTAL', 'BATCH', 'PREEMPTION'],\n"
"      status: ['ACCESERROR', 'BATCHER_TIMEOUT', 'BATCHER_PAUSE', 'BATCHER_FINISH', 'RTCERROR', 'RAMERROR', 'REVERSE', 'LOGFULL'],\n"
"      isr: ['DOUT0', 'DOUT1', 'DOUT2', 'BUZZER', 'HIGHFREQ', 'LOWFREQ', 'DUTY', 'PHASE']\n"
"    };\n"
"    /* display labels for the flag chips (bit order must match FLAGS) */\n"
"    const FLBL = {\n"
"      RATEQMAX: 'Расх>Qмакс', RATEHIGH: 'Расх>макс', RATELOW: 'Расх<мин',\n"
"      FLOW: 'Поток', TOTAL: 'Объём', GTOTAL: 'Общий объём', BATCH: 'Порция',\n"
"      PREEMPTION: 'Прерывание',\n"
"      ACCESERROR: 'Ошибка доступа', BATCHER_TIMEOUT: 'Таймаут порции',\n"
"      BATCHER_PAUSE: 'Порция: пауза', BATCHER_FINISH: 'Порция: конец',\n"
"      RTCERROR: 'Ошибка RTC', RAMERROR: 'Ошибка RAM', REVERSE: 'Реверс',\n"
"      LOGFULL: 'Журнал полон',\n"
"      DOUT0: 'Вых0', DOUT1: 'Вых1', DOUT2: 'Вых2', BUZZER: 'Звук',\n"
"      HIGHFREQ: 'Частота>', LOWFREQ: 'Частота<', DUTY: 'Скважность', PHASE: 'Фаза'\n"
"    };\n"
"    // const VFLOATS = ['frequency', 'rate_raw', 'rate_fast', 'rateMLPM', 'rate', 'total_plus', 'total_minus', 'total', 'total_sum', 'totalml_plus', 'totalml_minus', 'gtotal', 'gtotalml', 'kf_value', 'batch'];\n"
"    const VFLOATS = ['kf_value', 'batch'];\n"
"    const VUINTS = ['pulses_packet', 'pulses'];\n"
"    /* display labels only: the JSON keys stay the MeterData_t member\n"
"     * names, so the 'm' data itself is untouched */\n"
"    const LBL = {\n"
"      frequency: 'Частота, Гц',\n"
"      rate_raw: 'Расход (raw)',\n"
"      rate_fast: 'Расход (fast)',\n"
"      rateMLPM: 'Расход, мл/мин',\n"
"      rate: 'Расход',\n"
"      total_plus: 'Объём +',\n"
"      total_minus: 'Объём −',\n"
"      total: 'Объём',\n"
"      total_sum: 'Объём (сумма)',\n"
"      totalml_plus: 'Объём +, мл',\n"
"      totalml_minus: 'Объём −, мл',\n"
"      gtotal: 'Общий объём',\n"
"      gtotalml: 'Общий объём, мл',\n"
"      kf_value: 'K-фактор',\n"
"      batch: 'Порция',\n"
"      pulses_packet: 'Импульсы (пакет)',\n"
"      pulses: 'Импульсы',\n"
"      setpoint: 'Уставки (биты)',\n"
"      status: 'Состояние (биты)',\n"
"      isr: 'Флаги ISR (биты)'\n"
"    };\n"
"\n"
"    const prec7 = x => Number(x.toPrecision(7));\n"
"    const round2 = x => Number(x.toFixed(2));\n"
"    /*\n"
"     * ── CUSTOM VALUE WIDGETS ────────────────────────────────────────\n"
"     * A digital-parameter widget computed by a free-form formula:\n"
"     *   calc(d, C) - d = the whole live 'm' values object (fields are\n"
"     *   the names in VFLOATS/VUINTS above), C = the named constants\n"
"     *   from MY_CONST below. Returns a number.\n"
"     * To add your own widget by hand, add ONE line to CUSTOM, e.g.:\n"
"     *     total_x2: { calc: (d, C) => d.total * C.k, label: 'Объём ×k', on: true },\n"
"     * That's all: the widget auto-appears on the main screen and in\n"
"     * the \"Виджеты\" panel (a saved layout already in localStorage\n"
"     * picks the new entry up on the next page load).\n"
"     * 'on' is the initial state for a FIRST appearance only; later\n"
"     * on/off and drag order are the user's, kept in localStorage.\n"
"     */\n"
"    const MY_CONST = {\n"
"      my_const: 10\n"
"    };\n"
"    const CUSTOM = {\n"
"      // fast_plus_total: { calc: d => r7(d.rate_fast + 10) + d.total, label: 'Частота, Гц', on: true },\n"
"      frequency_hz: { calc: d => round2(d.frequency), label: 'Частота, Гц', on: true },\n"
"      with_const: { calc: (d, C) => prec7((d.rate_fast + 10) / 10 + d.total - C.my_const), label: 'с константой', on: true }\n"
"    };\n"
"    /*\n"
"     * ── FLOW WIDGET ─────────────────────────────────────────────────\n"
"     * Configurable rate widget (like the bar, configured in the panel):\n"
"     * input is rateMLPM (ml/min), the two combos pick the volume unit\n"
"     * and the time unit; the label composes itself (\"Расход, л/мин\").\n"
"     * The \"vol\" widget below is the same for gtotal (volume only).\n"
"     */\n"
"    const VOLU = { ml: 1, l: 1000, m3: 1000000 };   /* ml per volume unit */\n"
"    const VOLN = { ml: 'мл', l: 'л', m3: 'м³' };\n"
"    const TIMU = { s: 1 / 60, m: 1, h: 60, d: 1440 }; /* minutes per time unit */\n"
"    const TIMN = { s: 'с', m: 'мин', h: 'ч', d: 'сут' };\n"
"    /*\n"
"     * ── BAR WIDGET MODES ────────────────────────────────────────────\n"
"     * value source + the setpoint parameter that marks the 100% level\n"
"     * (resolved by name from /api/params, see paramsTick)\n"
"     */\n"
"    const BARM = {\n"
"      qmax: { n: 'Расход (Qmax)', src: 'rate', sp: 'Qmax,л' },\n"
"      rate: { n: 'Расход', src: 'rate', sp: 'Расход+' },\n"
"      total: { n: 'Объём', src: 'total', sp: 'Объём' },\n"
"      gtotal: { n: 'Общий', src: 'gtotal', sp: 'Общий' },\n"
"      dose: { n: 'Доза', src: 'batch', sp: 'Доза' }\n"
"    };\n"
"    let SP = {};   /* mode -> setpoint 100% value, refreshed with the tree */\n"
"    /* volume widget source modes over the totalml_plus/minus pair */\n"
"    const TOTM = {\n"
"      plus: { n: 'Объём +', c: d => d.totalml_plus },\n"
"      minus: { n: 'Объём −', c: d => d.totalml_minus },\n"
"      diff: { n: 'Объём', c: d => d.totalml_plus - d.totalml_minus },\n"
"      sum: { n: 'Объём (сумма)', c: d => d.totalml_plus + d.totalml_minus }\n"
"    };\n"
"    /*\n"
"     * ── BIT WIDGET ──────────────────────────────────────────────────\n"
"     * One flag bit as a lamp: src group (FLAGS above) + bit index,\n"
"     * col = the lamp color of the ACTIVE level. The label is the flag\n"
"     * name and wraps on spaces (narrow cards).\n"
"     */\n"
"    const BITCOL = ['#1d5c2f', '#a23b2e', '#2a5bdb', '#e3b341'];\n"
"    let vBuilt = false;\n"
"    /* rate history: ring of the last 600 s (the values poll is 1 Hz) */\n"
"    const RATE_N = 600;\n"
"    let rateHist = [], rateMin = 0, rateMax = 1;\n"
"    function ratePush(v) {\n"
"      rateHist.push(v);\n"
"      if (rateHist.length > RATE_N) rateHist.shift();\n"
"    }\n"
"    function rateDraw() {\n"
"      const cv = $('rateChart'); if (!cv) return;\n"
"      const dpr = window.devicePixelRatio || 1;\n"
"      const w = cv.offsetWidth, h = 120;\n"
"      if (cv.width !== w * dpr || cv.height !== h * dpr) { cv.width = w * dpr; cv.height = h * dpr }\n"
"      const g = cv.getContext('2d');\n"
"      g.setTransform(dpr, 0, 0, dpr, 0, 0);\n"
"      g.clearRect(0, 0, w, h);\n"
"      const n = rateHist.length;\n"
"      g.strokeStyle = '#2a3140'; g.lineWidth = 1;\n"
"      for (let k = 1; k < 4; k++) { const y = h * k / 4; g.beginPath(); g.moveTo(0, y); g.lineTo(w, y); g.stroke() }\n"
"      if (n < 2) { g.fillStyle = '#8b94a7'; g.font = '12px system-ui'; g.fillText('накопление данных…', 8, h / 2); return }\n"
"      let lo = Infinity, hi = -Infinity;\n"
"      for (const v of rateHist) { if (v < lo) lo = v; if (v > hi) hi = v }\n"
"      rateMin = lo; rateMax = hi;\n"
"      if (hi - lo < 1e-9) { lo -= 0.5; hi += 0.5 }\n"
"      const pad = (hi - lo) * 0.08; lo -= pad; hi += pad;\n"
"      const X = i => w * i / (RATE_N - 1), Y = v => h - 2 - (v - lo) / (hi - lo) * (h - 4);\n"
"      g.beginPath();\n"
"      const off = RATE_N - n; /* anchor right so the chart scrolls */\n"
"      for (let i = 0; i < n; i++) { const x = X(off + i), y = Y(rateHist[i]); i ? g.lineTo(x, y) : g.moveTo(x, y) }\n"
"      g.strokeStyle = '#7aa2f7'; g.lineWidth = 1.5; g.stroke();\n"
"      g.lineTo(X(RATE_N - 1), h); g.lineTo(X(off), h); g.closePath();\n"
"      g.fillStyle = 'rgba(122,162,247,0.15)'; g.fill();\n"
"      const last = rateHist[n - 1];\n"
"      g.fillStyle = '#d8dee9'; g.font = '12px ui-monospace,Consolas,monospace';\n"
"      g.fillText(last.toFixed(3), 8, 12);\n"
"      g.fillStyle = '#8b94a7';\n"
"      g.fillText('max ' + (rateMax).toFixed(3), w - 86, 12);\n"
"      g.fillText('min ' + (rateMin).toFixed(3), w - 86, h - 4);\n"
"    }\n"
"    window.addEventListener('resize', rateDraw);\n"
"    /*\n"
"     * Widgets: the main screen is a list of widget configs kept in\n"
"     * localStorage (\"widgets\"): {k: id, t: chart|val|bits|bar, src: data\n"
"     * key, on, min, max}. Base widgets are generated from the MeterData\n"
"     * members; \"bar\" is the torn-stripe progress bar. Drag & drop in the\n"
"     * edit mode reorders the array.\n"
"     */\n"
"    function baseWidgets() {\n"
"      const w = [{ k: 'rateChart', t: 'chart', src: 'rate', on: true },\n"
"      { k: 'bar_qmax', t: 'bar', mode: 'qmax', on: true }];\n"
"      for (const n of VFLOATS.concat(VUINTS)) w.push({ k: n, t: 'val', src: n, on: true });\n"
"      for (const n in FLAGS) w.push({ k: 'bits_' + n, t: 'bits', src: n, on: true });\n"
"      for (const id in CUSTOM) w.push({ k: id, t: 'cval', on: CUSTOM[id].on !== false });\n"
"      w.push({ k: 'flow_l_m', t: 'flow', vol: 'l', time: 'm', on: true });\n"
"      w.push({ k: 'vol_l', t: 'vol', vol: 'l', on: true });\n"
"      w.push({ k: 'tot_plus_l', t: 'tot', m: 'plus', vol: 'l', on: true });\n"
"      w.push({ k: 'bit_flow', t: 'bit', src: 'setpoint', b: 3, col: BITCOL[0], on: true });\n"
"      return w;\n"
"    }\n"
"    let widgets = null;\n"
"    function saveWidgets() { localStorage.setItem('widgets', JSON.stringify(widgets)) }\n"
"    function loadWidgets() {\n"
"      try { widgets = JSON.parse(localStorage.getItem('widgets')) } catch (e) { widgets = null }\n"
"      if (!Array.isArray(widgets)) {\n"
"        widgets = baseWidgets();\n"
"        /* one-time migration: keep the old drag order (\"vorder\") */\n"
"        try {\n"
"          const o = JSON.parse(localStorage.getItem('vorder'));\n"
"          if (Array.isArray(o))\n"
"            widgets.sort((a, b) => (o.indexOf(a.k) + 1 || 1e9) - (o.indexOf(b.k) + 1 || 1e9));\n"
"        } catch (e) { }\n"
"        saveWidgets();\n"
"      }\n"
"      /* drop configs whose source disappeared, add new data keys */\n"
"      widgets = widgets.filter(w => w.t === 'bar' || w.t === 'flow' || w.t === 'vol' || w.t === 'tot' || w.t === 'bit' || (w.t === 'cval' && CUSTOM[w.k]) ||\n"
"        (w.src && (w.src === 'rate' || VFLOATS.includes(w.src) || VUINTS.includes(w.src) || w.src in FLAGS)));\n"
"      for (const w of widgets) if (w.t === 'bar' && !BARM[w.mode]) w.mode = 'qmax';\n"
"      for (const w of widgets) if ((w.t === 'vol' || w.t === 'tot') && !VOLU[w.vol]) w.vol = 'l';\n"
"      for (const w of widgets) if (w.t === 'tot' && !TOTM[w.m]) w.m = 'plus';\n"
"      for (const w of widgets)\n"
"        if (w.t === 'bit' && (!(w.src in FLAGS) || !(w.b >= 0 && w.b < FLAGS[w.src].length))) { w.src = 'setpoint'; w.b = 0 }\n"
"      for (const w of widgets) if (w.t === 'bit' && !/^#[0-9a-fA-F]{6}$/.test(w.col || '')) w.col = BITCOL[0];\n"
"      for (const w of widgets) if (w.t === 'bar' && !BARM[w.mode]) w.mode = 'qmax';\n"
"      /* structural widgets (tied to the 'm' data or the CUSTOM block)\n"
"       * reappear if missing; the configurable ones (bar/flow/vol/tot)\n"
"       * are fully user-managed and STAY deleted */\n"
"      for (const b of baseWidgets())\n"
"        if (b.t !== 'bar' && b.t !== 'flow' && b.t !== 'vol' && b.t !== 'tot' &&\n"
"            !widgets.some(w => w.k === b.k))\n"
"          widgets.push(b);\n"
"    }\n"
"    function widgetName(w) {\n"
"      if (w.t === 'chart') return 'График: Расход, 10 мин';\n"
"      if (w.t === 'bar') return 'Бар: ' + (BARM[w.mode] ? BARM[w.mode].n : w.mode);\n"
"      if (w.t === 'cval') return (CUSTOM[w.k] && CUSTOM[w.k].label) || w.k;\n"
"      if (w.t === 'flow') return 'Расход, ' + VOLN[w.vol] + '/' + TIMN[w.time];\n"
"      if (w.t === 'vol') return 'Общий, ' + VOLN[w.vol];\n"
"      if (w.t === 'tot') return TOTM[w.m].n + ', ' + VOLN[w.vol];\n"
"      if (w.t === 'bit') return (FLBL[FLAGS[w.src][w.b]] || FLAGS[w.src][w.b]);\n"
"      return LBL[w.src] || w.src;\n"
"    }\n"
"    function widgetHtml(w) {\n"
"      if (w.t === 'chart')\n"
"        return '<div class=\"vcard chart\" data-k=\"' + w.k + '\"><div class=\"vname\">Расход, последние 10 мин</div><canvas id=\"rateChart\"></canvas></div>';\n"
"      if (w.t === 'val')\n"
"        return '<div class=\"vcard\" data-k=\"' + w.k + '\"><div class=\"vname\">' + (LBL[w.src] || w.src) + '</div><div class=\"vval\" id=\"vf_' + w.src + '\">—</div></div>';\n"
"      if (w.t === 'cval') /* custom: src × factor, label from CUSTOM */\n"
"        return '<div class=\"vcard\" data-k=\"' + w.k + '\"><div class=\"vname\">' + widgetName(w) + '</div><div class=\"vval\" id=\"vfc_' + w.k + '\">—</div></div>';\n"
"      if (w.t === 'flow') /* rateMLPM converted to vol/time units */\n"
"        return '<div class=\"vcard\" data-k=\"' + w.k + '\"><div class=\"vname\">' + widgetName(w) + '</div><div class=\"vval\" id=\"vfl_' + w.k + '\">—</div></div>';\n"
"      if (w.t === 'vol') /* gtotalml converted to the volume unit */\n"
"        return '<div class=\"vcard\" data-k=\"' + w.k + '\"><div class=\"vname\">' + widgetName(w) + '</div><div class=\"vval\" id=\"vvv_' + w.k + '\">—</div></div>';\n"
"      if (w.t === 'tot') /* totalml_plus/minus combination -> volume unit */\n"
"        return '<div class=\"vcard\" data-k=\"' + w.k + '\"><div class=\"vname\">' + widgetName(w) + '</div><div class=\"vval\" id=\"vtv_' + w.k + '\">—</div></div>';\n"
"      if (w.t === 'bit') /* single flag bit as a lamp, label wraps */\n"
"        return '<div class=\"vcard wbit\" data-k=\"' + w.k + '\"><div class=\"vname\">' + widgetName(w) + '</div><div class=\"bitlamp\" id=\"bl_' + w.k + '\"></div></div>';\n"
"      if (w.t === 'bits') {\n"
"        let inner = '';\n"
"        FLAGS[w.src].forEach((b, k) => inner += '<span class=\"bit\" id=\"vb_' + w.src + '_' + k + '\" title=\"' + b + '\">' + (FLBL[b] || b) + '</span>');\n"
"        return '<div class=\"vcard wide\" data-k=\"' + w.k + '\"><div class=\"vname\">' + (LBL[w.src] || w.src) + '</div><div id=\"vb_' + w.src + '\">' + inner + '</div></div>';\n"
"      }\n"
"      /* bar: torn-stripe progress bar clamped to min..max, no value text */\n"
"      return '<div class=\"vcard wbar\" data-k=\"' + w.k + '\"><div class=\"vname\">' + widgetName(w).replace('Бар: ', '') + '<span class=\"bpct\" id=\"bp_' + w.k + '\"></span></div><div class=\"hbar\"><div class=\"hfill\" id=\"hf_' + w.k + '\"></div></div></div>';\n"
"    }\n"
"    function vBuild() {\n"
"      loadWidgets();\n"
"      $('values').innerHTML = widgets.filter(w => w.on).map(widgetHtml).join('');\n"
"      vBuilt = true; rateDraw(); setDrag(); renderPanel();\n"
"    }\n"
"    let editing = false;\n"
"    function toggleEdit() {\n"
"      editing = !editing;\n"
"      document.body.className = editing ? 'edit' : '';\n"
"      $('btnEdit').classList.toggle('act', editing);\n"
"      setDrag();\n"
"    }\n"
"    function setDrag() {\n"
"      const el = $('values'); if (!el) return;\n"
"      [...el.children].forEach(c => c.draggable = editing);\n"
"    }\n"
"    let dragK = null;\n"
"    document.addEventListener('dragstart', e => {\n"
"      const c = e.target.closest && e.target.closest('.vcard');\n"
"      if (!editing || !c) return;\n"
"      dragK = c.dataset.k; c.classList.add('dragging');\n"
"      e.dataTransfer.effectAllowed = 'move';\n"
"    });\n"
"    document.addEventListener('dragend', e => {\n"
"      const c = e.target.closest && e.target.closest('.vcard');\n"
"      if (c) c.classList.remove('dragging');\n"
"      dragK = null;\n"
"    });\n"
"    document.addEventListener('dragover', e => {\n"
"      if (!editing || !dragK) return;\n"
"      if (e.target.closest && e.target.closest('.vcard')) e.preventDefault();\n"
"    });\n"
"    document.addEventListener('drop', e => {\n"
"      const c = e.target.closest && e.target.closest('.vcard');\n"
"      if (!editing || !dragK || !c || c.dataset.k === dragK) return;\n"
"      e.preventDefault();\n"
"      const src = document.querySelector('.vcard[data-k=\"' + dragK + '\"]');\n"
"      if (!src) return;\n"
"      /* insert before/after by the pointer half of the target card */\n"
"      const r = c.getBoundingClientRect();\n"
"      const after = (e.clientY - r.top) > r.height / 2 || (e.clientX - r.left) > r.width / 2;\n"
"      c.parentNode.insertBefore(src, after ? c.nextSibling : c);\n"
"      /* the DOM order of the enabled cards IS the widget order */\n"
"      const ord = [...$('values').children].map(x => x.dataset.k);\n"
"      widgets.sort((a, b) =>\n"
"        (ord.indexOf(a.k) + 1 || 1e9) - (ord.indexOf(b.k) + 1 || 1e9));\n"
"      saveWidgets();\n"
"    });\n"
"    /* ---------------------------------------------------------------- */\n"
"    /* the \"Виджеты\" panel: enable/disable, bar min/max, add/remove     */\n"
"    function toggleW() {\n"
"      const p = $('wpanel');\n"
"      p.hidden = !p.hidden;\n"
"      $('btnW').classList.toggle('act', !p.hidden);\n"
"      renderPanel();\n"
"    }\n"
"    function renderPanel() {\n"
"      const p = $('wlist'); if (!p) return;\n"
"      let h = '';\n"
"      widgets.forEach((w, i) => {\n"
"        h += '<div class=\"wrow\"><label><input type=\"checkbox\"' + (w.on ? ' checked' : '') +\n"
"          ' onchange=\"wToggle(' + i + ',this.checked)\"> ' + widgetName(w) + '</label>';\n"
"        if (w.t === 'bar') {\n"
"          let sb = '<select onchange=\"wFlow(' + i + ',\\'mode\\',this.value)\">';\n"
"          for (const m in BARM) sb += '<option value=\"' + m + '\"' + (w.mode === m ? ' selected' : '') + '>' + BARM[m].n + '</option>';\n"
"          h += ' ' + sb + '</select> <button class=\"warn\" onclick=\"wDel(' + i + ')\">удалить</button>';\n"
"        }\n"
"        if (w.t === 'flow') {\n"
"          const sel = (which, map, names) => {\n"
"            let s = '<select onchange=\"wFlow(' + i + ',\\'' + which + '\\',this.value)\">';\n"
"            for (const u in map) s += '<option value=\"' + u + '\"' + (w[which] === u ? ' selected' : '') + '>' + names[u] + '</option>';\n"
"            return s + '</select>';\n"
"          };\n"
"          h += ' объём ' + sel('vol', VOLU, VOLN) + ' время ' + sel('time', TIMU, TIMN) +\n"
"            ' <button class=\"warn\" onclick=\"wDel(' + i + ')\">удалить</button>';\n"
"        }\n"
"        if (w.t === 'vol') {\n"
"          let s = '<select onchange=\"wFlow(' + i + ',\\'vol\\',this.value)\">';\n"
"          for (const u in VOLU) s += '<option value=\"' + u + '\"' + (w.vol === u ? ' selected' : '') + '>' + VOLN[u] + '</option>';\n"
"          h += ' объём ' + s + '</select>' +\n"
"            ' <button class=\"warn\" onclick=\"wDel(' + i + ')\">удалить</button>';\n"
"        }\n"
"        if (w.t === 'tot') {\n"
"          let sm = '<select onchange=\"wFlow(' + i + ',\\'m\\',this.value)\">';\n"
"          for (const u in TOTM) sm += '<option value=\"' + u + '\"' + (w.m === u ? ' selected' : '') + '>' + TOTM[u].n + '</option>';\n"
"          let sv = '<select onchange=\"wFlow(' + i + ',\\'vol\\',this.value)\">';\n"
"          for (const u in VOLU) sv += '<option value=\"' + u + '\"' + (w.vol === u ? ' selected' : '') + '>' + VOLN[u] + '</option>';\n"
"          h += ' ' + sm + '</select> ' + sv + '</select>' +\n"
"            ' <button class=\"warn\" onclick=\"wDel(' + i + ')\">удалить</button>';\n"
"        }\n"
"        if (w.t === 'bit') {\n"
"          let sg = '<select onchange=\"wBit(' + i + ',\\'src\\',this.value)\">';\n"
"          for (const g in FLAGS) sg += '<option value=\"' + g + '\"' + (w.src === g ? ' selected' : '') + '>' + (LBL[g] || g) + '</option>';\n"
"          let sb = '<select onchange=\"wBit(' + i + ',\\'b\\',this.value)\">';\n"
"          FLAGS[w.src].forEach((f, bi) => sb += '<option value=\"' + bi + '\"' + (w.b === bi ? ' selected' : '') + '>' + (FLBL[f] || f) + '</option>');\n"
"          h += ' ' + sg + '</select> ' + sb + '</select>' +\n"
"            ' цвет <input type=\"color\" value=\"' + w.col + '\" onchange=\"wBit(' + i + ',\\'col\\',this.value)\">' +\n"
"            ' <button class=\"warn\" onclick=\"wDel(' + i + ')\">удалить</button>';\n"
"        }\n"
"        h += '</div>';\n"
"      });\n"
"      const opts = VFLOATS.map(n => '<option value=\"' + n + '\">' + (LBL[n] || n) + '</option>').join('');\n"
"      h += '<div class=\"wrow\">＋ барграф <select id=\"nbMode\">';\n"
"      for (const m in BARM) h += '<option value=\"' + m + '\"' + (m === 'qmax' ? ' selected' : '') + '>' + BARM[m].n + '</option>';\n"
"      h += '</select> <button onclick=\"wAddBar()\">Добавить</button></div>';\n"
"      h += '<div class=\"wrow\">＋ расход <select id=\"nwVol\">' +\n"
"        '<option value=\"ml\">мл</option><option value=\"l\" selected>л</option><option value=\"m3\">м³</option></select>' +\n"
"        ' / <select id=\"nwTime\"><option value=\"s\">с</option><option value=\"m\" selected>мин</option>' +\n"
"        '<option value=\"h\">ч</option><option value=\"d\">сут</option></select>' +\n"
"        ' <button onclick=\"wAddFlow()\">Добавить</button></div>';\n"
"      h += '<div class=\"wrow\">＋ общий объём <select id=\"nvVol\">' +\n"
"        '<option value=\"ml\">мл</option><option value=\"l\" selected>л</option><option value=\"m3\">м³</option></select>' +\n"
"        ' <button onclick=\"wAddVol()\">Добавить</button></div>';\n"
"      h += '<div class=\"wrow\">＋ объём <select id=\"ntMode\">' +\n"
"        '<option value=\"plus\" selected>Объём +</option><option value=\"minus\">Объём −</option>' +\n"
"        '<option value=\"diff\">Объём (+−)</option><option value=\"sum\">Объём (сумма)</option></select>' +\n"
"        ' <select id=\"ntVol\"><option value=\"ml\">мл</option><option value=\"l\" selected>л</option><option value=\"m3\">м³</option></select>' +\n"
"        ' <button onclick=\"wAddTot()\">Добавить</button></div>';\n"
"      h += '<div class=\"wrow\">＋ бит <select id=\"nbiSrc\">';\n"
"      for (const g in FLAGS) h += '<option value=\"' + g + '\"' + (g === 'setpoint' ? ' selected' : '') + '>' + (LBL[g] || g) + '</option>';\n"
"      h += '</select> <select id=\"nbiBit\"></select>' +\n"
"        ' цвет <input id=\"nbiCol\" type=\"color\" value=\"' + BITCOL[0] + '\">' +\n"
"        ' <button onclick=\"wAddBit()\">Добавить</button></div>';\n"
"      p.innerHTML = h;\n"
"      { /* prefill the bit list of the \"＋ бит\" row */\n"
"        const g = $('nbiSrc').value, sel = $('nbiBit');\n"
"        sel.innerHTML = FLAGS[g].map((f, bi) => '<option value=\"' + bi + '\">' + (FLBL[f] || f) + '</option>').join('');\n"
"      }\n"
"    }\n"
"    function wToggle(i, on) { widgets[i].on = on; saveWidgets(); vBuild() }\n"
"    function wFlow(i, which, v) { widgets[i][which] = v; saveWidgets(); vBuild() }\n"
"    function wDel(i) { widgets.splice(i, 1); saveWidgets(); vBuild() }\n"
"    function wAddBar() {\n"
"      widgets.push({ k: 'bar' + Date.now(), t: 'bar', mode: $('nbMode').value, on: true });\n"
"      saveWidgets(); vBuild();\n"
"    }\n"
"    function wAddFlow() {\n"
"      widgets.push({ k: 'flow' + Date.now(), t: 'flow', vol: $('nwVol').value, time: $('nwTime').value, on: true });\n"
"      saveWidgets(); vBuild();\n"
"    }\n"
"    function wAddVol() {\n"
"      widgets.push({ k: 'vol' + Date.now(), t: 'vol', vol: $('nvVol').value, on: true });\n"
"      saveWidgets(); vBuild();\n"
"    }\n"
"    function wAddTot() {\n"
"      widgets.push({ k: 'tot' + Date.now(), t: 'tot', m: $('ntMode').value, vol: $('ntVol').value, on: true });\n"
"      saveWidgets(); vBuild();\n"
"    }\n"
"    function wAddBit() {\n"
"      widgets.push({ k: 'bit' + Date.now(), t: 'bit', src: $('nbiSrc').value,\n"
"                     b: parseInt($('nbiBit').value) || 0, col: $('nbiCol').value, on: true });\n"
"      saveWidgets(); vBuild();\n"
"    }\n"
"    /* bit combo: rebuild the bit list when the source group changes */\n"
"    function wBit(i, which, v) {\n"
"      widgets[i][which] = which === 'b' ? parseInt(v) : v;\n"
"      saveWidgets(); vBuild();\n"
"    }\n"
"    document.addEventListener('change', e => {\n"
"      if (e.target.id !== 'nbiSrc') return;\n"
"      const sel = $('nbiBit');\n"
"      sel.innerHTML = FLAGS[e.target.value]\n"
"        .map((f, bi) => '<option value=\"' + bi + '\">' + (FLBL[f] || f) + '</option>').join('');\n"
"    });\n"
"    function vApply(d) {\n"
"      const barLo = vApply.lo || (vApply.lo = {}), barHi = vApply.hi || (vApply.hi = {});\n"
"      for (const n of VFLOATS) { const e = $('vf_' + n); if (e && d[n] !== undefined) e.textContent = d[n] }\n"
"      for (const n of VUINTS) { const e = $('vf_' + n); if (e && d[n] !== undefined) e.textContent = d[n] }\n"
"      for (const n in FLAGS) { const v = d[n] || 0; FLAGS[n].forEach((b, k) => { const e = $('vb_' + n + '_' + k); if (e) e.className = 'bit' + ((v >> k) & 1 ? ' on' : '') }) }\n"
"      for (const w of widgets || []) {\n"
"        if (w.t !== 'cval' || !w.on) continue;\n"
"        const c = CUSTOM[w.k], e = $('vfc_' + w.k);\n"
"        if (c && e && c.calc) {\n"
"          /* no forced formatting here: the calc's own rounding (e.g.\n"
"           * Number(x.toPrecision(4))) is what the card must show */\n"
"          const v = c.calc(d, MY_CONST);\n"
"          if (isFinite(v)) e.textContent = String(v)\n"
"        }\n"
"      }\n"
"      /* flow widgets: rateMLPM (ml/min) -> chosen volume / time units */\n"
"      for (const w of widgets || []) {\n"
"        if (w.t !== 'flow' || !w.on) continue;\n"
"        const e = $('vfl_' + w.k);\n"
"        if (e && d.rateMLPM !== undefined)\n"
"          e.textContent = Number((d.rateMLPM / VOLU[w.vol] * TIMU[w.time]).toPrecision(4))\n"
"      }\n"
"      /* volume widgets: gtotalml -> chosen volume unit, no time factor */\n"
"      for (const w of widgets || []) {\n"
"        if (w.t !== 'vol' || !w.on) continue;\n"
"        const e = $('vvv_' + w.k);\n"
"        if (e && d.gtotalml !== undefined)\n"
"          e.textContent = Number((d.gtotalml / VOLU[w.vol]).toPrecision(4))\n"
"      }\n"
"      /* bit widgets: the lamp lights with the chosen color when the bit is 1 */\n"
"      for (const w of widgets || []) {\n"
"        if (w.t !== 'bit' || !w.on) continue;\n"
"        const e = $('bl_' + w.k);\n"
"        if (e && d[w.src] !== undefined) {\n"
"          const on = (d[w.src] >> w.b) & 1;\n"
"          e.style.background = on ? w.col : '#0e1116';\n"
"          e.style.color = w.col;               /* currentColor glow */\n"
"          e.classList.toggle('on', !!on);\n"
"        }\n"
"      }\n"
"      /* tot widgets: totalml_plus/minus combination -> volume unit */\n"
"      for (const w of widgets || []) {\n"
"        if (w.t !== 'tot' || !w.on) continue;\n"
"        const e = $('vtv_' + w.k), m = TOTM[w.m];\n"
"        if (e && m && d.totalml_plus !== undefined && d.totalml_minus !== undefined) {\n"
"          const v = m.c(d) / VOLU[w.vol];\n"
"          if (isFinite(v)) e.textContent = Number(v.toPrecision(4))\n"
"        }\n"
"      }\n"
"      for (const w of widgets || []) {\n"
"        if (w.t !== 'bar' || !w.on) continue;\n"
"        const m = BARM[w.mode], f = $('hf_' + w.k);\n"
"        const v = m ? d[m.src] : undefined;\n"
"        if (f && v !== undefined) {\n"
"          /* 100% = the setpoint parameter of the mode (paramsTick);\n"
"           * fallback until it is known: running min/max like the chart */\n"
"          let hi = SP[w.mode];\n"
"          if (!(hi > 0)) {\n"
"            if (!(w.k in barLo) || v < barLo[w.k]) barLo[w.k] = v;\n"
"            if (!(w.k in barHi) || v > barHi[w.k]) barHi[w.k] = v;\n"
"            hi = barHi[w.k];\n"
"            if (hi - (barLo[w.k] || 0) < 1e-9) hi = (barLo[w.k] || 0) + 1;\n"
"          }\n"
"          const pct = Math.max(0, Math.min(100, v / hi * 100));\n"
"          f.style.width = pct.toFixed(1) + '%';\n"
"          const t = $('bp_' + w.k);\n"
"          if (t) t.textContent = pct.toFixed(0) + '%';\n"
"        }\n"
"      }\n"
"    }\n"
"    async function valuesTick() {\n"
"      try {\n"
"        const d = await (await fetch('/api/values')).json();\n"
"        if (d.link !== undefined) {\n"
"          $('link').textContent = d.link ? 'UART: связь есть' : 'UART: нет связи';\n"
"          $('link').className = 'tag ' + (d.link ? 'ok' : 'bad');\n"
"        }\n"
"        if (!d.ok) { return }\n"
"        if (!vBuilt) vBuild();\n"
"        vApply(d);\n"
"        if (d.rate !== undefined) { ratePush(d.rate); rateDraw() }\n"
"      } catch (e) { }\n"
"    }\n"
"    setInterval(valuesTick, 200); valuesTick();\n"
"    async function infoTick() {\n"
"      try {\n"
"        const r = await (await fetch('/api/info')).json();\n"
"        $('fw').textContent = r.fw + ' · параметров: ' + r.count;\n"
"        $('ip').textContent = r.ip;\n"
"        $('rss').textContent = r.ap ? r.rssi + ' dBm' : r.ssid + ': ' + r.rssi + ' dBm';\n"
"        $('upt').textContent = 'uptime ' + hms(r.uptime); $('heap').textContent = 'heap ' + (r.heap / 1024 | 0) + ' KiB';\n"
"      } catch (e) { }\n"
"    }\n"
"    /* setpoints for the bar 100% levels: floats from the settings tree;\n"
"     * \"Qmax,л\" is matched by name anywhere, the rest strictly inside the\n"
"     * \"Уставки\" submenu (those names repeat across the tree) */\n"
"    async function paramsTick() {\n"
"      try {\n"
"        const d = await (await fetch('/api/params')).json();\n"
"        SP = {};\n"
"        for (const p of d.params) {\n"
"          if (p.t !== 0 || !p.w || !p.n) continue;\n"
"          for (const m in BARM)\n"
"            if (p.n === BARM[m].sp && (m === 'qmax' || p.tb === 'Уставки'))\n"
"              SP[m] = parseFloat(p.v);\n"
"        }\n"
"      } catch (e) { }\n"
"    }\n"
"    paramsTick(); setInterval(paramsTick, 30000);\n"
"    async function rescan() { await fetch('/api/rescan', { method: 'POST' }); infoTick(); paramsTick() }\n"
"    function rebootDev() { if (confirm('Перезагрузить прибор?')) fetch('/api/reboot', { method: 'POST' }) }\n"
"    infoTick(); setInterval(infoTick, 5000);\n"
"  </script>\n"
"</body>\n"
"\n"
"</html>\n";

static const char PAGE_SETTINGS[] =
"<!doctype html>\n"
"<html lang=\"ru\">\n"
"\n"
"<head>\n"
"  <meta charset=\"utf-8\">\n"
"  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"  <title>SKE-02 Настройки</title>\n"
"  <style>\n"
"    body {\n"
"      font: 13px/1.45 system-ui, sans-serif;\n"
"      background: #14171c;\n"
"      color: #d8dee9;\n"
"      margin: 0;\n"
"      padding: 12px\n"
"    }\n"
"\n"
"    header {\n"
"      display: flex;\n"
"      flex-wrap: wrap;\n"
"      gap: 8px;\n"
"      align-items: center;\n"
"      margin-bottom: 10px\n"
"    }\n"
"\n"
"    h1 {\n"
"      font-size: 18px;\n"
"      margin: 0 8px 0 0\n"
"    }\n"
"\n"
"    .tag {\n"
"      background: #2a3140;\n"
"      border-radius: 4px;\n"
"      padding: 2px 8px;\n"
"      font-size: 12px;\n"
"      white-space: nowrap\n"
"    }\n"
"\n"
"    .ok {\n"
"      background: #1d5c2f\n"
"    }\n"
"\n"
"    .bad {\n"
"      background: #6c2431\n"
"    }\n"
"\n"
"    button {\n"
"      background: #2a5bdb;\n"
"      color: #fff;\n"
"      border: 0;\n"
"      border-radius: 4px;\n"
"      padding: 5px 5px;\n"
"      cursor: pointer;\n"
"      font-size: 12px\n"
"    }\n"
"\n"
"    input,\n"
"    select {\n"
"      background: #0e1116;\n"
"      color: #d8dee9;\n"
"      border: 1px solid #39414f;\n"
"      border-radius: 4px;\n"
"      padding: 4px 4px;\n"
"      box-sizing: border-box\n"
"    }\n"
"\n"
"    #filter {\n"
"      width: 200px\n"
"    }\n"
"\n"
"    #nav {\n"
"      display: flex;\n"
"      flex-wrap: wrap;\n"
"      gap: 6px;\n"
"      margin-bottom: 10px\n"
"    }\n"
"\n"
"    #nav button {\n"
"      background: #2a3140;\n"
"      font-size: 12px;\n"
"      padding: 8px 8px\n"
"    }\n"
"\n"
"    #nav button.act {\n"
"      background: #2a5bdb\n"
"    }\n"
"\n"
"    .tabs {\n"
"      display: flex;\n"
"      flex-wrap: wrap;\n"
"      gap: 4px;\n"
"      border-bottom: 2px solid #2a3140;\n"
"      margin-bottom: 8px\n"
"    }\n"
"\n"
"    .tabs button {\n"
"      background: transparent;\n"
"      color: #8b94a7;\n"
"      border: 0;\n"
"      border-bottom: 2px solid transparent;\n"
"      border-radius: 6px 6px 0 0;\n"
"      padding: 7px 14px;\n"
"      cursor: pointer;\n"
"      font-size: 12px\n"
"    }\n"
"\n"
"    .tabs button.act {\n"
"      color: #d8dee9;\n"
"      background: #1b202a;\n"
"      border-bottom-color: #2a5bdb\n"
"    }\n"
"\n"
"    .subtabs {\n"
"      display: flex;\n"
"      flex-wrap: wrap;\n"
"      gap: 4px;\n"
"      margin: 0 0 8px 8px\n"
"    }\n"
"\n"
"    .subtabs button {\n"
"      background: #232a38;\n"
"      color: #8b94a7;\n"
"      border: 0;\n"
"      border-radius: 10px;\n"
"      padding: 3px 5px;\n"
"      cursor: pointer;\n"
"      font-size: 12px\n"
"    }\n"
"\n"
"    .subtabs button.act {\n"
"      background: #1d5c2f;\n"
"      color: #d8dee9\n"
"    }\n"
"\n"
"    table {\n"
"      width: 100%;\n"
"      border-collapse: collapse\n"
"    }\n"
"\n"
"    td,\n"
"    th {\n"
"      padding: 5px 5px;\n"
"      border-top: 1px solid #2a3140;\n"
"      text-align: left;\n"
"      vertical-align: middle\n"
"    }\n"
"\n"
"    th {\n"
"      color: #8b94a7;\n"
"      font-weight: 500;\n"
"      font-size: 12px\n"
"    }\n"
"\n"
"    .val {\n"
"      font-family: ui-monospace, Consolas, monospace;\n"
"      white-space: nowrap\n"
"    }\n"
"\n"
"    .stale {\n"
"      color: #8b94a7\n"
"    }\n"
"\n"
"    .ctl {\n"
"      text-align: right;\n"
"      vertical-align: middle\n"
"    }\n"
"\n"
"    .where {\n"
"      color: #8b94a7;\n"
"      font-size: 12px;\n"
"      margin-top: 1px\n"
"    }\n"
"\n"
"    .set {\n"
"      display: flex;\n"
"      gap: 6px;\n"
"      align-items: center;\n"
"      flex-wrap: wrap;\n"
"      justify-content: flex-end\n"
"    }\n"
"\n"
"    .set input[type=number],\n"
"    .set input[type=text] {\n"
"      width: 110px\n"
"    }\n"
"\n"
"    .set input.fnum {\n"
"      width: 130px\n"
"    }\n"
"\n"
"    .set select {\n"
"      max-width: 170px\n"
"    }\n"
"\n"
"    .t2 {\n"
"      width: 56px !important;\n"
"      text-align: center\n"
"    }\n"
"\n"
"    .dv {\n"
"      color: #8b94a7\n"
"    }\n"
"\n"
"    #actions {\n"
"      display: flex;\n"
"      flex-wrap: wrap;\n"
"      gap: 6px;\n"
"      align-items: center;\n"
"      margin: 0 0 8px 0\n"
"    }\n"
"\n"
"    #secPw {\n"
"      width: 140px\n"
"    }\n"
"\n"
"    button.run {\n"
"      background: #1d5c2f\n"
"    }\n"
"\n"
"    tr.dirty td {\n"
"      background: #2a2517\n"
"    }\n"
"\n"
"    .flash {\n"
"      color: #7aa2f7\n"
"    }\n"
"\n"
"    .lingrid {\n"
"      display: grid;\n"
"      grid-template-columns: auto auto auto auto;\n"
"      gap: 8px 18px;\n"
"      align-items: center;\n"
"      background: #1b202a;\n"
"      border: 1px solid #2a3140;\n"
"      border-radius: 8px;\n"
"      padding: 12px;\n"
"      margin-bottom: 8px\n"
"    }\n"
"\n"
"    .lingrid label {\n"
"      color: #8b94a7;\n"
"      font-size: 12px;\n"
"      white-space: nowrap\n"
"    }\n"
"\n"
"    .lingrid .set {\n"
"      justify-content: flex-start\n"
"    }\n"
"\n"
"    .lingrid input.dirty {\n"
"      border-color: #e3b341\n"
"    }\n"
"  </style>\n"
"</head>\n"
"\n"
"<body>\n"
"  <header>\n"
"    <h1>SKE-02 Настройки</h1>\n"
"    <span id=\"link\" class=\"tag\">…</span><span id=\"fw\" class=\"tag\"></span>\n"
"    <a href=\"/\"><button>&#8592; Мониторинг</button></a>\n"
"    <a href=\"/wifi\"><button>Wi-Fi</button></a>\n"
"  </header>\n"
"  <div id=\"nav\"></div>\n"
"  <div id=\"tabs\"></div>\n"
"  <div id=\"subtabs\"></div>\n"
"  <div id=\"actions\">\n"
"    <input id=\"secPw\" type=\"password\" inputmode=\"numeric\" maxlength=\"6\" placeholder=\"пароль меню\" oninput=\"pwInput()\">\n"
"    <button id=\"btnApply\" onclick=\"applyAll()\">Применить</button>\n"
"    <button id=\"btnRefresh\" onclick=\"refreshAll()\">Обновить</button>\n"
"    <span id=\"applyMsg\" class=\"flash\"></span>\n"
"  </div>\n"
"  <div id=\"bar\">\n"
"    <input id=\"filter\" placeholder=\"фильтр по имени или id\" oninput=\"applyFilter()\">\n"
"  </div>\n"
"  <div id=\"sections\">\n"
"    <p>Опрос прибора…</p>\n"
"  </div>\n"
"  <script>\n"
"    const COMMON = '\\x01';              /* pseudo tab for params directly in the section */\n"
"    let P = [], SECT = [], built = '', cur = 0, curT = {}, curS = {}, pwMap = {}, dirty = new Set();\n"
"    const $ = i => document.getElementById(i);\n"
"    const esc = s => String(s).replace(/[&<>\"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '\"': '&quot;' }[c]));\n"
"    const p2 = v => String(v).padStart(2, '0');\n"
"    /* manual refresh only: values never change under the user's fingers */\n"
"    let retryT = 0;\n"
"    async function tick() {\n"
"      try {\n"
"        const r = await (await fetch('/api/info')).json();\n"
"        $('link').textContent = r.link ? 'UART: связь есть' : 'UART: нет связи';\n"
"        $('link').className = 'tag ' + (r.link ? 'ok' : 'bad');\n"
"        $('fw').textContent = r.fw + ' · параметров: ' + r.count;\n"
"        const d = await (await fetch('/api/params')).json();\n"
"        P = d.params; SECT = d.sections; dirty = new Set();\n"
"        render(d.count + '|' + d.params.length + '|' + d.sections.length + '|' + d.rc);\n"
"        applyFilter();\n"
"        /* the tree is empty while a rescan/listing is in flight on the\n"
"         * gateway - poll instead of demanding a wiring check */\n"
"        if (!P.length && !retryT)\n"
"          retryT = setTimeout(() => { retryT = 0; tick() }, 3000);\n"
"      } catch (e) { }\n"
"    }\n"
"    /* the per-section password field follows the active section */\n"
"    function pwInput() { pwMap[cur] = $('secPw').value }\n"
"    function syncPw() { $('secPw').value = pwMap[cur] || '' }\n"
"    function mark(i) {\n"
"      dirty.add(i);\n"
"      const tr = document.querySelector('tr[data-i=\"' + i + '\"]');\n"
"      if (tr) tr.className = 'dirty';\n"
"      const w = $('w' + i);            /* grid cells have no tr: mark the input */\n"
"      if (w) w.classList.add('dirty');\n"
"    }\n"
"    function unmark(i) {\n"
"      const tr = document.querySelector('tr[data-i=\"' + i + '\"]');\n"
"      if (tr) tr.className = '';\n"
"      const w = $('w' + i);\n"
"      if (w) w.classList.remove('dirty');\n"
"    }\n"
"    /* edit widget html for the parameter type (no per-row apply button:\n"
"     * edits accumulate and are sent by the section-wide \"Применить\") */\n"
"    function widget(q) {\n"
"      if (!q.w) return '';\n"
"      const i = q.i, m = ' oninput=\"mark(' + i + ')\" onchange=\"mark(' + i + ')\"';\n"
"      if ((q.t === 10 || q.t === 11) && q.o && q.o.length) {\n"
"        let h = '<select id=\"w' + i + '\"' + m + '>';\n"
"        q.o.forEach((s, k) => h += '<option value=\"' + k + '\"' + (String(k) === String(q.r) ? ' selected' : '') + '>' + esc(s) + '</option>');\n"
"        return '<div class=\"set\">' + h + '</select></div>';\n"
"      }\n"
"      if (q.m) return '<div class=\"set\"><input id=\"w' + i + '\" type=\"password\" maxlength=\"6\" inputmode=\"numeric\" placeholder=\"******\"' + m + '></div>';\n"
"      if (q.t === 0) return '<div class=\"set\"><input id=\"w' + i + '\" type=\"text\" class=\"fnum\" inputmode=\"decimal\" maxlength=\"12\" title=\"' + esc((q.lo || '?') + ' .. ' + (q.hi || '?')) + '\" value=\"' + esc(q.v) + '\"' + m + '></div>';\n"
"      if (q.t === 1) return '<div class=\"set\"><input id=\"w' + i + '\" type=\"text\" maxlength=\"6\" inputmode=\"numeric\" title=\"' + esc((q.lo || '?') + ' .. ' + (q.hi || '?')) + '\" value=\"' + esc(q.v) + '\"' + m + '></div>';\n"
"      if (q.t === 2 || q.t === 3) {\n"
"        const m2 = q.v.split(/[:.]/);\n"
"        if (q.t === 2) return '<div class=\"set\"><input class=\"t2\" id=\"wh' + i + '\" type=\"number\" min=\"0\" max=\"23\" step=\"1\" value=\"' + esc(m2[0]) + '\"' + m + '><span class=\"dv\">:</span><input class=\"t2\" id=\"wm' + i + '\" type=\"number\" min=\"0\" max=\"59\" step=\"1\" value=\"' + esc(m2[1]) + '\"' + m + '></div>';\n"
"        return '<div class=\"set\"><input class=\"t2\" id=\"wd' + i + '\" type=\"number\" min=\"1\" max=\"31\" step=\"1\" value=\"' + esc(m2[0]) + '\"' + m + '><span class=\"dv\">.</span><input class=\"t2\" id=\"wm2' + i + '\" type=\"number\" min=\"1\" max=\"12\" step=\"1\" value=\"' + esc(m2[1]) + '\"' + m + '><span class=\"dv\">.</span><input class=\"t2\" id=\"wy' + i + '\" type=\"number\" min=\"0\" max=\"99\" step=\"1\" value=\"' + esc(m2[2]) + '\"' + m + '></div>';\n"
"      }\n"
"      const st = ' min=\"' + (q.lo !== '' ? esc(q.lo) : '0') + '\" max=\"' + (q.hi !== '' ? esc(q.hi) : '65535') + '\"';\n"
"      return '<div class=\"set\"><input id=\"w' + i + '\" type=\"number\" step=\"1\"' + st + ' value=\"' + esc(q.v) + '\"' + m + '></div>';\n"
"    }\n"
"    /* one table row: name | editor (RO values as text, CMD items as a button) */\n"
"    function row(q, where) {\n"
"      let ctrl;\n"
"      if (q.cx) ctrl = '<button class=\"run\" onclick=\"runParam(' + q.i + ')\">Выполнить</button>';\n"
"      else ctrl = q.w ? widget(q) : '<span class=\"val' + (q.a > 90 ? ' stale' : '') + '\" id=\"v' + q.i + '\">' + esc(q.v) + '</span>';\n"
"      return '<tr data-n=\"' + esc((q.n + ' ' + q.i).toLowerCase()) + '\" data-i=\"' + q.i + '\"><td>' + esc(q.n || ('P' + q.i)) +\n"
"        (where ? '<div class=\"where\">' + esc(where) + '</div>' : '') + '</td><td class=\"ctl\">' + ctrl + '</td></tr>';\n"
"    }\n"
"    const THEAD = '<tr><th>Параметр</th><th></th></tr>';\n"
"    /*\n"
"     * The server names the owning L2 menu explicitly (\"tb\"), because the\n"
"     * firmware prints subtrees before the parent's own params and the id\n"
"     * order alone cannot recover the hierarchy. L3 = the nearest submenu\n"
"     * when its level is exactly 3.\n"
"     */\n"
"    function decorate(arr) {\n"
"      const rows = [];\n"
"      for (const q of arr) {\n"
"        rows.push({ q, l2: q.tb || COMMON, l3: (q.gl === 3 && q.g) ? q.g : '' });\n"
"      }\n"
"      return rows;\n"
"    }\n"
"    let curTab = COMMON;                 /* active L2 tab name of the section */\n"
"    function render(fp) {\n"
"      if (!P.length) { $('tabs').innerHTML = ''; $('subtabs').innerHTML = ''; $('sections').innerHTML = '<p>Опрос прибора… если через минуту пусто — проверьте подключение UART и питание, затем нажмите «Обновить».</p>'; built = fp; return }\n"
"      let h = '';\n"
"      SECT.forEach((s, k) => h += '<button class=\"' + (k === cur ? 'act' : '') + '\" onclick=\"go(' + k + ')\">' + esc(s) + '</button>');\n"
"      $('nav').innerHTML = h;\n"
"      if (cur >= SECT.length) cur = 0;\n"
"      syncPw();\n"
"      const rows = decorate(P.filter(q => q.s === cur || SECT.length <= 1));\n"
"      const tabs = [...new Set(rows.map(r => r.l2))];\n"
"      if (!(cur in curT) || curT[cur] >= tabs.length) curT[cur] = 0;\n"
"      const t = tabs[curT[cur]];\n"
"      curTab = t;\n"
"      const tr = rows.filter(r => r.l2 === t);\n"
"      const subs = [...new Set(tr.map(r => r.l3))];\n"
"      const sk = cur + '|' + t;\n"
"      if (!(sk in curS) || curS[sk] >= subs.length) curS[sk] = 0;\n"
"      const s = subs[curS[sk]];\n"
"      h = '';\n"
"      tabs.forEach((n, k) => h += '<button class=\"' + (n === t ? 'act' : '') + '\" onclick=\"go2(' + k + ')\">' + esc(n === COMMON ? 'Общие' : n) + '</button>');\n"
"      $('tabs').innerHTML = '<div class=\"tabs\">' + h + '</div>';\n"
"      h = '';\n"
"      if (subs.length > 1 || subs[0] !== '')\n"
"        subs.forEach((n, k) => h += '<button class=\"' + (n === s ? 'act' : '') + '\" onclick=\"go3(' + k + ')\">' + esc(n || 'Общие') + '</button>');\n"
"      $('subtabs').innerHTML = h ? '<div class=\"subtabs\">' + h + '</div>' : '';\n"
"      const vis = tr.filter(r => r.l3 === s);\n"
"      /*\n"
"       * Linearization directions (\"Прямое/Реверс направление\") hold the F/V\n"
"       * calibration pairs: render them as an F|V grid, one pair per row\n"
"       * (F01|V01, F02|V02, ...), instead of a long two-column list.\n"
"       */\n"
"      const linRe = /^[FV]\\d\\d/;\n"
"      if (vis.length >= 4 && vis.every(r => linRe.test(r.q.n))) {\n"
"        const F = {}, V = {};\n"
"        for (const r of vis) (r.q.n[0] === 'F' ? F : V)[r.q.n.slice(1, 3)] = r.q;\n"
"        const keys = [...new Set([...Object.keys(F), ...Object.keys(V)])].sort();\n"
"        const cell = q => q ? '<label>' + esc(q.n) + '</label>' + widget(q) : '<label></label><span></span>';\n"
"        h = '<div class=\"lingrid\">';\n"
"        for (const k of keys) h += cell(F[k]) + cell(V[k]);\n"
"        h += '</div>';\n"
"      } else {\n"
"        h = '<table>' + THEAD;\n"
"        for (const r of vis) h += row(r.q);\n"
"        h += '</table>';\n"
"      }\n"
"      $('sections').innerHTML = h; built = fp;\n"
"    }\n"
"    /* search view: filter matches anywhere, across all sections and tabs */\n"
"    function renderSearch(f) {\n"
"      let h = '<table>' + THEAD;\n"
"      for (const q of P) {\n"
"        if (!(q.n + ' ' + q.i).toLowerCase().includes(f)) continue;\n"
"        const sec = q.s >= 0 && q.s < SECT.length ? SECT[q.s] : '';\n"
"        h += row(q, sec ? (sec + (q.g ? ' · ' + q.g : '')) : '');\n"
"      }\n"
"      h += '</table>';\n"
"      $('sections').innerHTML = h || '<p>Ничего не найдено.</p>';\n"
"      $('tabs').innerHTML = ''; $('subtabs').innerHTML = '';\n"
"    }\n"
"    function go(k) { cur = k; render(built); syncPw(); applyFilter() }\n"
"    function go2(k) { curT[cur] = k; applyFilter() }\n"
"    function go3(k) { curS[cur + '|' + curTab] = k; applyFilter() }\n"
"    function applyFilter() {\n"
"      const f = $('filter').value.trim().toLowerCase();\n"
"      if (!f) { render(built); return }\n"
"      renderSearch(f);\n"
"    }\n"
"    function curVal(q) {\n"
"      const i = q.i, g = x => $(x + i);\n"
"      if (q.t === 10 || q.t === 11) return g('w').value;\n"
"      if (q.t === 2) return p2(g('wh').value) + ':' + p2(g('wm').value);\n"
"      if (q.t === 3) return p2(g('wd').value) + '.' + p2(g('wm2').value) + '.' + p2(g('wy').value);\n"
"      return g('w').value;\n"
"    }\n"
"    function flash(msg) {\n"
"      $('applyMsg').textContent = msg;\n"
"      setTimeout(() => { if ($('applyMsg').textContent === msg) $('applyMsg').textContent = '' }, 2500);\n"
"    }\n"
"    /* apply every edited parameter, unlocking its menu with the section\n"
"     * password first; the first failure aborts the rest */\n"
"    async function applyAll() {\n"
"      const ids = [...dirty];\n"
"      if (!ids.length) { flash('нет изменений'); return }\n"
"      $('btnApply').disabled = true;\n"
"      let done = 0;\n"
"      for (const i of ids) {\n"
"        const q = P.find(x => x.i === i);\n"
"        if (!q) continue;\n"
"        const body = 'id=' + i + '&v=' + encodeURIComponent(curVal(q)) + '&pw=' + encodeURIComponent(pwMap[q.s] || '');\n"
"        try {\n"
"          const r = await (await fetch('/api/set', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body })).json();\n"
"          if (!r.ok) { alert('«' + (q.n || ('P' + i)) + '»: ' + r.error); break }\n"
"          dirty.delete(i); done++;\n"
"          unmark(i);\n"
"          /* keep the local cache in sync with the device read-back, so a\n"
"           * tab switch re-renders the new value, not the pre-edit one */\n"
"          if (r.value !== undefined) {\n"
"            q.v = r.value;\n"
"            if ((q.t === 10 || q.t === 11) && q.o)\n"
"              q.r = q.o.findIndex(s => s === r.value);\n"
"          }\n"
"          if (q.m) { const w = $('w' + i); if (w) w.value = '' }\n"
"        } catch (e) { alert('нет ответа от шлюза'); break }\n"
"      }\n"
"      $('btnApply').disabled = false;\n"
"      if (done) flash('применено: ' + done);\n"
"    }\n"
"    /* run a menu command item ('x'), unlocked with its section password */\n"
"    async function runParam(i) {\n"
"      const q = P.find(x => x.i === i);\n"
"      if (!q || !q.cx) return;\n"
"      if (!confirm('Выполнить «' + (q.n || ('P' + i)) + '»?')) return;\n"
"      try {\n"
"        const r = await (await fetch('/api/run', {\n"
"          method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n"
"          body: 'id=' + i + '&pw=' + encodeURIComponent(pwMap[q.s] || '')\n"
"        })).json();\n"
"        if (!r.ok) alert('«' + (q.n || ('P' + i)) + '»: ' + r.error);\n"
"        else flash('команда выполнена');\n"
"      } catch (e) { alert('нет ответа от шлюза') }\n"
"    }\n"
"    /* \"Обновить\": full 'l' listing on the device (settings poll is on-demand\n"
"     * only), then the page reloads from the refreshed cache */\n"
"    async function refreshAll() {\n"
"      if (dirty.size && !confirm('Есть несохранённые изменения. Обновить без применения?')) return;\n"
"      const b = $('btnRefresh'); b.disabled = true; b.textContent = 'Обновление…';\n"
"      try {\n"
"        const r = await (await fetch('/api/refresh', { method: 'POST' })).json();\n"
"        if (!r.ok) alert('Прибор не ответил на запрос листинга');\n"
"        await tick();\n"
"      } catch (e) { alert('нет ответа от шлюза') }\n"
"      b.disabled = false; b.textContent = 'Обновить';\n"
"    }\n"
"    tick();\n"
"  </script>\n"
"</body>\n"
"\n"
"</html>\n";

#endif /* GW_PAGES_H */
