/*
 * Web pages - hand-maintained source of the RTOS port;
 * edit directly.
 */
#ifndef GW_PAGES_H
#define GW_PAGES_H

static const char PAGE_WIFI[] =
"<!doctype html>\n"
"<html lang=\"ru\"><head><meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>SKE-02 Gateway - Wi-Fi</title>\n"
"<style>\n"
"body{font:14px/1.45 system-ui,sans-serif;background:#14171c;color:#d8dee9;max-width:520px;margin:24px auto;padding:0 14px}\n"
"h1{font-size:18px}label{display:block;margin:12px 0 4px;color:#8b94a7}\n"
"input{width:100%;box-sizing:border-box;background:#0e1116;color:#d8dee9;border:1px solid #39414f;border-radius:6px;padding:8px}\n"
"button{margin-top:14px;background:#2a5bdb;color:#fff;border:0;border-radius:6px;padding:9px 22px;cursor:pointer;font-size:15px}\n"
"table{width:100%;border-collapse:collapse;margin-top:6px}\n"
"td{padding:6px 8px;border-top:1px solid #2a3140}\n"
".pick{background:#233047;color:#d8dee9;border:1px solid #39414f;border-radius:6px;padding:3px 10px;cursor:pointer}\n"
".dbm{color:#8b94a7}\n"
"</style></head><body>\n"
"<h1>Настройка Wi-Fi шлюза SKE-02</h1>\n"
"<form method=\"POST\" action=\"/save\">\n"
"<label>SSID сети</label><input name=\"ssid\" id=\"ssid\" maxlength=\"32\" autocapitalize=\"off\" autocorrect=\"off\" spellcheck=\"false\" required>\n"
"<label>Пароль (для открытой сети оставьте пустым)</label><input name=\"pass\" type=\"password\" maxlength=\"64\" autocapitalize=\"off\" autocorrect=\"off\">\n"
"<button type=\"submit\">Подключиться</button>\n"
"</form>\n"
"<h3>Найденные сети</h3><div id=\"nets\">сканирование…</div>\n"
"<script>\n"
"let NETS=[];\n"
"const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));\n"
"async function load(restart){\n"
" if(restart)await fetch('/scan?restart=1');\n"
" const r=await (await fetch('/scan')).json();\n"
" if(r.running){setTimeout(()=>load(0),1500);return}\n"
" NETS=r.nets;\n"
" let h='<table>';\n"
" NETS.forEach((n,i)=>{\n"
"  h+='<tr><td>'+esc(n.s)+'</td><td class=\"dbm\">'+n.r+' dBm</td><td>'+\n"
"     (n.e?'🔒':'')+'</td><td><button class=\"pick\" onclick=\"pick('+i+')\">выбрать</button></td></tr>';\n"
" });\n"
" document.getElementById('nets').innerHTML=h+'</table>';\n"
"}\n"
"function pick(i){document.getElementById('ssid').value=NETS[i].s}\n"
"load(1);\n"
"</script></body></html>\n";

static const char PAGE_CSS[] =
"body{font:14px system-ui,sans-serif\n";

static const char PAGE_INDEX[] =
"<!doctype html>\n"
"<html lang=\"ru\"><head><meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>SKE-02 Gateway</title>\n"
"<style>\n"
"body{font:14px/1.45 system-ui,sans-serif;background:#14171c;color:#d8dee9;margin:0;padding:12px}\n"
"header{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin-bottom:10px}\n"
"h1{font-size:18px;margin:0 8px 0 0}\n"
".tag{background:#2a3140;border-radius:6px;padding:2px 8px;font-size:12px;white-space:nowrap}\n"
".ok{background:#1d5c2f}.bad{background:#6c2431}\n"
"button{background:#2a5bdb;color:#fff;border:0;border-radius:6px;padding:5px 12px;cursor:pointer;font-size:13px}\n"
"button.warn{background:#a23b2e}\n"
"input,select{background:#0e1116;color:#d8dee9;border:1px solid #39414f;border-radius:6px;padding:4px 8px;box-sizing:border-box}\n"
"#filter{width:200px}\n"
"#bar{display:flex;flex-wrap:wrap;gap:6px;align-items:center;margin-bottom:10px}\n"
"#nav{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:10px}\n"
"#nav button{background:#2a3140;font-size:14px;padding:8px 18px}\n"
"#nav button.act{background:#2a5bdb}\n"
".tabs{display:flex;flex-wrap:wrap;gap:4px;border-bottom:2px solid #2a3140;margin-bottom:8px}\n"
".tabs button{background:transparent;color:#8b94a7;border:0;border-bottom:2px solid transparent;border-radius:6px 6px 0 0;padding:7px 14px;cursor:pointer;font-size:14px}\n"
".tabs button.act{color:#d8dee9;background:#1b202a;border-bottom-color:#2a5bdb}\n"
".subtabs{display:flex;flex-wrap:wrap;gap:4px;margin:0 0 8px 8px}\n"
".subtabs button{background:#232a38;color:#8b94a7;border:0;border-radius:10px;padding:3px 12px;cursor:pointer;font-size:12px}\n"
".subtabs button.act{background:#1d5c2f;color:#d8dee9}\n"
"details{background:#1b202a;border:1px solid #2a3140;border-radius:8px;margin-bottom:8px}\n"
"summary{padding:8px 12px;cursor:pointer;font-weight:600}\n"
"table{width:100%;border-collapse:collapse}\n"
"td,th{padding:5px 10px;border-top:1px solid #2a3140;text-align:left;vertical-align:middle}\n"
"th{color:#8b94a7;font-weight:500;font-size:12px}\n"
".val{font-family:ui-monospace,Consolas,monospace;white-space:nowrap}\n"
".stale{color:#8b94a7}\n"
".ctl{text-align:right;vertical-align:middle}\n"
".where{color:#8b94a7;font-size:11px;margin-top:1px}\n"
"input.fnum{width:130px;text-align:right}\n"
".set{display:flex;gap:6px;align-items:center;flex-wrap:wrap;justify-content:flex-end}\n"
".set input[type=number],.set input[type=text]{width:110px}\n"
".set input.fnum{width:130px}\n"
".set select{max-width:170px}\n"
".t2{width:56px!important;text-align:center}\n"
".dv{color:#8b94a7}\n"
"#actions{display:flex;flex-wrap:wrap;gap:6px;align-items:center;margin:0 0 8px 0}\n"
"#secPw{width:140px}\n"
"button.run{background:#1d5c2f}\n"
"tr.dirty td{background:#2a2517}\n"
".flash{color:#7aa2f7}\n"
"#debug{display:flex;flex-wrap:wrap;gap:6px;align-items:center;margin:0 0 8px 0;\n"
" padding:4px 8px;border:1px dashed #39414f;border-radius:8px;color:#8b94a7;font-size:12px}\n"
"#debug .tag{background:transparent;border:1px solid #2a3140;padding:1px 6px}\n"
"#debug button{font-size:12px;padding:4px 10px}\n"
"body.nosettings #nav,body.nosettings #tabs,body.nosettings #subtabs,\n"
"body.nosettings #actions,body.nosettings #bar,body.nosettings #sections{display:none}\n"
"#values{display:grid;grid-template-columns:repeat(auto-fill,minmax(168px,1fr));gap:8px;margin:0 0 10px 0}\n"
".vcard{background:#1b202a;border:1px solid #2a3140;border-radius:8px;padding:8px 12px}\n"
".vname{color:#8b94a7;font-size:11px}\n"
".vval{font-family:ui-monospace,Consolas,monospace;font-size:17px;white-space:nowrap}\n"
".vcard.wide{grid-column:span 2}\n"
".vcard.chart{grid-column:1/-1}\n"
".vcard.chart canvas{width:100%;height:120px;display:block}\n"
".bit{display:inline-block;font-size:10px;padding:1px 7px;border-radius:9px;margin:1px;background:#232a38;color:#565f6e}\n"
".bit.on{background:#1d5c2f;color:#d8dee9}\n"
"#btnSettings{font-size:14px;padding:8px 18px}\n"
"#btnSettings.act{background:#1d5c2f}\n"
".lingrid{display:grid;grid-template-columns:auto auto auto auto;gap:8px 18px;\n"
" align-items:center;background:#1b202a;border:1px solid #2a3140;border-radius:8px;padding:12px;margin-bottom:8px}\n"
".lingrid label{color:#8b94a7;font-size:12px;white-space:nowrap}\n"
".lingrid .set{justify-content:flex-start}\n"
".lingrid input.dirty{border-color:#e3b341}\n"
"</style></head><body class=\"nosettings\">\n"
"<header>\n"
" <h1>SKE-02 Gateway</h1>\n"
" <span id=\"link\" class=\"tag\">…</span><span id=\"fw\" class=\"tag\"></span>\n"
" <button id=\"btnSettings\" onclick=\"toggleSettings()\">&#9881; Настройки</button>\n"
" <button class=\"warn\" onclick=\"rebootDev()\">Перезагрузить прибор</button>\n"
" <a href=\"/wifi\"><button>Wi-Fi</button></a>\n"
"</header>\n"
"<div id=\"values\"></div>\n"
"<div id=\"debug\">\n"
" отладочная панель\n"
" <button onclick=\"rescan()\">Пересканировать</button>\n"
" <span class=\"tag\" id=\"ip\"></span><span class=\"tag\" id=\"rss\"></span>\n"
" <span class=\"tag\" id=\"upt\"></span><span class=\"tag\" id=\"heap\"></span>\n"
"</div>\n"
"<div id=\"nav\"></div>\n"
"<div id=\"tabs\"></div>\n"
"<div id=\"subtabs\"></div>\n"
"<div id=\"actions\">\n"
" <input id=\"secPw\" type=\"password\" inputmode=\"numeric\" maxlength=\"6\" placeholder=\"пароль меню\" oninput=\"pwInput()\">\n"
" <button id=\"btnApply\" onclick=\"applyAll()\">Применить</button>\n"
" <button id=\"btnRefresh\" onclick=\"refreshAll()\">Обновить</button>\n"
" <span id=\"applyMsg\" class=\"flash\"></span>\n"
"</div>\n"
"<div id=\"bar\">\n"
" <input id=\"filter\" placeholder=\"фильтр по имени или id\" oninput=\"applyFilter()\">\n"
"</div>\n"
"<div id=\"sections\"><p>Опрос прибора…</p></div>\n"
"<script>\n"
"const COMMON='\\x01';              /* pseudo tab for params directly in the section */\n"
"let P=[],SECT=[],built='',cur=0,curT={},curS={},pwMap={},dirty=new Set();\n"
"const $=i=>document.getElementById(i);\n"
"const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));\n"
"const p2=v=>String(v).padStart(2,'0');\n"
"function hms(t){const s=t%60,m=(t/60|0)%60,h=t/3600|0;return h?h+'ч '+m+'м':m?m+'м '+s+'с':s+'с'}\n"
"/* live values window: MeterData_t fields, names as the struct members;\n"
" * bitwise members render as FSETPOINT_/FSTATUS_/FISR_ flag chips */\n"
"const FLAGS={\n"
" setpoint:['RATEQMAX','RATEHIGH','RATELOW','FLOW','TOTAL','GTOTAL','BATCH','PREEMPTION'],\n"
" status:['ACCESERROR','BATCHER_TIMEOUT','BATCHER_PAUSE','BATCHER_FINISH','RTCERROR','RAMERROR','REVERSE','LOGFULL'],\n"
" isr:['DOUT0','DOUT1','DOUT2','BUZZER','HIGHFREQ','LOWFREQ','DUTY','PHASE']};\n"
"const VFLOATS=['frequency','rate_raw','rate_fast','rateMLPM','rate','total_plus','total_minus','total','total_sum','totalml_plus','totalml_minus','gtotal','gtotalml','kf_value','batch'];\n"
"const VUINTS=['pulses_packet','pulses'];\n"
"let vBuilt=false;\n"
"/* rate history: ring of the last 600 s (the values poll is 1 Hz) */\n"
"const RATE_N=600;\n"
"let rateHist=[],rateMin=0,rateMax=1;\n"
"function ratePush(v){\n"
" rateHist.push(v);\n"
" if(rateHist.length>RATE_N)rateHist.shift();\n"
"}\n"
"function rateDraw(){\n"
" const cv=$('rateChart');if(!cv)return;\n"
" const dpr=window.devicePixelRatio||1;\n"
" const w=cv.offsetWidth,h=120;\n"
" if(cv.width!==w*dpr||cv.height!==h*dpr){cv.width=w*dpr;cv.height=h*dpr}\n"
" const g=cv.getContext('2d');\n"
" g.setTransform(dpr,0,0,dpr,0,0);\n"
" g.clearRect(0,0,w,h);\n"
" const n=rateHist.length;\n"
" g.strokeStyle='#2a3140';g.lineWidth=1;\n"
" for(let k=1;k<4;k++){const y=h*k/4;g.beginPath();g.moveTo(0,y);g.lineTo(w,y);g.stroke()}\n"
" if(n<2){g.fillStyle='#8b94a7';g.font='12px system-ui';g.fillText('накопление данных…',8,h/2);return}\n"
" let lo=Infinity,hi=-Infinity;\n"
" for(const v of rateHist){if(v<lo)lo=v;if(v>hi)hi=v}\n"
" rateMin=lo;rateMax=hi;\n"
" if(hi-lo<1e-9){lo-=0.5;hi+=0.5}\n"
" const pad=(hi-lo)*0.08;lo-=pad;hi+=pad;\n"
" const X=i=>w*i/(RATE_N-1),Y=v=>h-2-(v-lo)/(hi-lo)*(h-4);\n"
" g.beginPath();\n"
" const off=RATE_N-n; /* anchor right so the chart scrolls */\n"
" for(let i=0;i<n;i++){const x=X(off+i),y=Y(rateHist[i]);i?g.lineTo(x,y):g.moveTo(x,y)}\n"
" g.strokeStyle='#7aa2f7';g.lineWidth=1.5;g.stroke();\n"
" g.lineTo(X(RATE_N-1),h);g.lineTo(X(off),h);g.closePath();\n"
" g.fillStyle='rgba(122,162,247,0.15)';g.fill();\n"
" const last=rateHist[n-1];\n"
" g.fillStyle='#d8dee9';g.font='12px ui-monospace,Consolas,monospace';\n"
" g.fillText(last.toFixed(3),8,12);\n"
" g.fillStyle='#8b94a7';\n"
" g.fillText('max '+(rateMax).toFixed(3),w-86,12);\n"
" g.fillText('min '+(rateMin).toFixed(3),w-86,h-4);\n"
"}\n"
"window.addEventListener('resize',rateDraw);\n"
"function vBuild(){\n"
" let h='<div class=\"vcard chart\"><div class=\"vname\">rate, последние 10 мин</div><canvas id=\"rateChart\"></canvas></div>';\n"
" for(const n of VFLOATS)h+='<div class=\"vcard\"><div class=\"vname\">'+n+'</div><div class=\"vval\" id=\"vf_'+n+'\">—</div></div>';\n"
" for(const n of VUINTS)h+='<div class=\"vcard\"><div class=\"vname\">'+n+'</div><div class=\"vval\" id=\"vf_'+n+'\">—</div></div>';\n"
" for(const n in FLAGS){\n"
"  h+='<div class=\"vcard wide\"><div class=\"vname\">'+n+'</div><div id=\"vb_'+n+'\">';\n"
"  FLAGS[n].forEach((b,k)=>h+='<span class=\"bit\" id=\"vb_'+n+'_'+k+'\">'+b+'</span>');\n"
"  h+='</div></div>';\n"
" }\n"
" $('values').innerHTML=h;vBuilt=true;rateDraw();\n"
"}\n"
"function vApply(d){\n"
" for(const n of VFLOATS){const e=$('vf_'+n);if(e&&d[n]!==undefined)e.textContent=d[n]}\n"
" for(const n of VUINTS){const e=$('vf_'+n);if(e&&d[n]!==undefined)e.textContent=d[n]}\n"
" for(const n in FLAGS){const v=d[n]||0;FLAGS[n].forEach((b,k)=>{const e=$('vb_'+n+'_'+k);if(e)e.className='bit'+((v>>k)&1?' on':'')})}\n"
"}\n"
"async function valuesTick(){\n"
" try{\n"
"  const d=await (await fetch('/api/values')).json();\n"
"  if(d.link!==undefined){\n"
"   $('link').textContent=d.link?'UART: связь есть':'UART: нет связи';\n"
"   $('link').className='tag '+(d.link?'ok':'bad');\n"
"  }\n"
"  if(!d.ok){return}\n"
"  if(!vBuilt)vBuild();\n"
"  vApply(d);\n"
"  if(d.rate!==undefined){ratePush(d.rate);rateDraw()}\n"
" }catch(e){}\n"
"}\n"
"setInterval(valuesTick,200);valuesTick();\n"
"/* the whole parameter tree (4 first-level menus, tabs, apply bar) lives\n"
" * behind the \"⚙ Настройки\" toggle - the main page stays clean */\n"
"let settingsOpen=false;\n"
"function toggleSettings(){\n"
" settingsOpen=!settingsOpen;\n"
" document.body.className=settingsOpen?'':'nosettings';\n"
" $('btnSettings').classList.toggle('act',settingsOpen);\n"
"}\n"
"/* manual refresh only: values never change under the user's fingers */\n"
"async function tick(){\n"
" try{\n"
"  const r=await (await fetch('/api/info')).json();\n"
"  $('link').textContent=r.link?'UART: связь есть':'UART: нет связи';\n"
"  $('link').className='tag '+(r.link?'ok':'bad');\n"
"  $('fw').textContent=r.fw+' · параметров: '+r.count;\n"
"  $('ip').textContent=r.ip;\n"
"  $('rss').textContent=r.ap?r.rssi+' dBm':r.ssid+': '+r.rssi+' dBm';\n"
"  $('upt').textContent='uptime '+hms(r.uptime);$('heap').textContent='heap '+(r.heap/1024|0)+' KiB';\n"
"  const d=await (await fetch('/api/params')).json();\n"
"  P=d.params;SECT=d.sections;dirty=new Set();\n"
"  render(d.count+'|'+d.params.length+'|'+d.sections.length+'|'+d.rc);\n"
"  applyFilter();\n"
" }catch(e){}\n"
"}\n"
"/* the per-section password field follows the active section */\n"
"function pwInput(){pwMap[cur]=$('secPw').value}\n"
"function syncPw(){$('secPw').value=pwMap[cur]||''}\n"
"function mark(i){\n"
" dirty.add(i);\n"
" const tr=document.querySelector('tr[data-i=\"'+i+'\"]');\n"
" if(tr)tr.className='dirty';\n"
" const w=$('w'+i);            /* grid cells have no tr: mark the input */\n"
" if(w)w.classList.add('dirty');\n"
"}\n"
"function unmark(i){\n"
" const tr=document.querySelector('tr[data-i=\"'+i+'\"]');\n"
" if(tr)tr.className='';\n"
" const w=$('w'+i);\n"
" if(w)w.classList.remove('dirty');\n"
"}\n"
"/* edit widget html for the parameter type (no per-row apply button:\n"
" * edits accumulate and are sent by the section-wide \"Применить\") */\n"
"function widget(q){\n"
" if(!q.w)return '';\n"
" const i=q.i,m=' oninput=\"mark('+i+')\" onchange=\"mark('+i+')\"';\n"
" if((q.t===10||q.t===11)&&q.o&&q.o.length){\n"
"  let h='<select id=\"w'+i+'\"'+m+'>';\n"
"  q.o.forEach((s,k)=>h+='<option value=\"'+k+'\"'+(String(k)===String(q.r)?' selected':'')+'>'+esc(s)+'</option>');\n"
"  return '<div class=\"set\">'+h+'</select></div>';\n"
" }\n"
" if(q.m)return '<div class=\"set\"><input id=\"w'+i+'\" type=\"password\" maxlength=\"6\" inputmode=\"numeric\" placeholder=\"******\"'+m+'></div>';\n"
" if(q.t===0)return '<div class=\"set\"><input id=\"w'+i+'\" type=\"text\" class=\"fnum\" inputmode=\"decimal\" maxlength=\"12\" title=\"'+esc((q.lo||'?')+' .. '+(q.hi||'?'))+'\" value=\"'+esc(q.v)+'\"'+m+'></div>';\n"
" if(q.t===1)return '<div class=\"set\"><input id=\"w'+i+'\" type=\"text\" maxlength=\"6\" inputmode=\"numeric\" title=\"'+esc((q.lo||'?')+' .. '+(q.hi||'?'))+'\" value=\"'+esc(q.v)+'\"'+m+'></div>';\n"
" if(q.t===2||q.t===3){\n"
"  const m2=q.v.split(/[:.]/);\n"
"  if(q.t===2)return '<div class=\"set\"><input class=\"t2\" id=\"wh'+i+'\" type=\"number\" min=\"0\" max=\"23\" step=\"1\" value=\"'+esc(m2[0])+'\"'+m+'><span class=\"dv\">:</span><input class=\"t2\" id=\"wm'+i+'\" type=\"number\" min=\"0\" max=\"59\" step=\"1\" value=\"'+esc(m2[1])+'\"'+m+'></div>';\n"
"  return '<div class=\"set\"><input class=\"t2\" id=\"wd'+i+'\" type=\"number\" min=\"1\" max=\"31\" step=\"1\" value=\"'+esc(m2[0])+'\"'+m+'><span class=\"dv\">.</span><input class=\"t2\" id=\"wm2'+i+'\" type=\"number\" min=\"1\" max=\"12\" step=\"1\" value=\"'+esc(m2[1])+'\"'+m+'><span class=\"dv\">.</span><input class=\"t2\" id=\"wy'+i+'\" type=\"number\" min=\"0\" max=\"99\" step=\"1\" value=\"'+esc(m2[2])+'\"'+m+'></div>';\n"
" }\n"
" const st=' min=\"'+(q.lo!==''?esc(q.lo):'0')+'\" max=\"'+(q.hi!==''?esc(q.hi):'65535')+'\"';\n"
" return '<div class=\"set\"><input id=\"w'+i+'\" type=\"number\" step=\"1\"'+st+' value=\"'+esc(q.v)+'\"'+m+'></div>';\n"
"}\n"
"/* one table row: name | editor (RO values as text, CMD items as a button) */\n"
"function row(q,where){\n"
" let ctrl;\n"
" if(q.cx)ctrl='<button class=\"run\" onclick=\"runParam('+q.i+')\">Выполнить</button>';\n"
" else ctrl=q.w?widget(q):'<span class=\"val'+(q.a>90?' stale':'')+'\" id=\"v'+q.i+'\">'+esc(q.v)+'</span>';\n"
" return '<tr data-n=\"'+esc((q.n+' '+q.i).toLowerCase())+'\" data-i=\"'+q.i+'\"><td>'+esc(q.n||('P'+q.i))+\n"
"  (where?'<div class=\"where\">'+esc(where)+'</div>':'')+'</td><td class=\"ctl\">'+ctrl+'</td></tr>';\n"
"}\n"
"const THEAD='<tr><th>Параметр</th><th></th></tr>';\n"
"/*\n"
" * The server names the owning L2 menu explicitly (\"tb\"), because the\n"
" * firmware prints subtrees before the parent's own params and the id\n"
" * order alone cannot recover the hierarchy. L3 = the nearest submenu\n"
" * when its level is exactly 3.\n"
" */\n"
"function decorate(arr){\n"
" const rows=[];\n"
" for(const q of arr){\n"
"  rows.push({q,l2:q.tb||COMMON,l3:(q.gl===3&&q.g)?q.g:''});\n"
" }\n"
" return rows;\n"
"}\n"
"let curTab=COMMON;                 /* active L2 tab name of the section */\n"
"function render(fp){\n"
" if(!P.length){$('tabs').innerHTML='';$('subtabs').innerHTML='';$('sections').innerHTML='<p>Прибор не найден: проверьте подключение UART и питание, затем нажмите «Пересканировать».</p>';built=fp;return}\n"
" let h='';\n"
" SECT.forEach((s,k)=>h+='<button class=\"'+(k===cur?'act':'')+'\" onclick=\"go('+k+')\">'+esc(s)+'</button>');\n"
" $('nav').innerHTML=h;\n"
" if(cur>=SECT.length)cur=0;\n"
" syncPw();\n"
" const rows=decorate(P.filter(q=>q.s===cur||SECT.length<=1));\n"
" const tabs=[...new Set(rows.map(r=>r.l2))];\n"
" if(!(cur in curT)||curT[cur]>=tabs.length)curT[cur]=0;\n"
" const t=tabs[curT[cur]];\n"
" curTab=t;\n"
" const tr=rows.filter(r=>r.l2===t);\n"
" const subs=[...new Set(tr.map(r=>r.l3))];\n"
" const sk=cur+'|'+t;\n"
" if(!(sk in curS)||curS[sk]>=subs.length)curS[sk]=0;\n"
" const s=subs[curS[sk]];\n"
" h='';\n"
" tabs.forEach((n,k)=>h+='<button class=\"'+(n===t?'act':'')+'\" onclick=\"go2('+k+')\">'+esc(n===COMMON?'Общие':n)+'</button>');\n"
" $('tabs').innerHTML='<div class=\"tabs\">'+h+'</div>';\n"
" h='';\n"
" if(subs.length>1||subs[0]!=='')\n"
"  subs.forEach((n,k)=>h+='<button class=\"'+(n===s?'act':'')+'\" onclick=\"go3('+k+')\">'+esc(n||'Общие')+'</button>');\n"
" $('subtabs').innerHTML=h?'<div class=\"subtabs\">'+h+'</div>':'';\n"
" const vis=tr.filter(r=>r.l3===s);\n"
" /*\n"
"  * Linearization directions (\"Прямое/Реверс направление\") hold the F/V\n"
"  * calibration pairs: render them as an F|V grid, one pair per row\n"
"  * (F01|V01, F02|V02, ...), instead of a long two-column list.\n"
"  */\n"
" const linRe=/^[FV]\\d\\d/;\n"
" if(vis.length>=4&&vis.every(r=>linRe.test(r.q.n))){\n"
"  const F={},V={};\n"
"  for(const r of vis)(r.q.n[0]==='F'?F:V)[r.q.n.slice(1,3)]=r.q;\n"
"  const keys=[...new Set([...Object.keys(F),...Object.keys(V)])].sort();\n"
"  const cell=q=>q?'<label>'+esc(q.n)+'</label>'+widget(q):'<label></label><span></span>';\n"
"  h='<div class=\"lingrid\">';\n"
"  for(const k of keys)h+=cell(F[k])+cell(V[k]);\n"
"  h+='</div>';\n"
" }else{\n"
"  h='<table>'+THEAD;\n"
"  for(const r of vis)h+=row(r.q);\n"
"  h+='</table>';\n"
" }\n"
" $('sections').innerHTML=h;built=fp;\n"
"}\n"
"/* search view: filter matches anywhere, across all sections and tabs */\n"
"function renderSearch(f){\n"
" let h='<table>'+THEAD;\n"
" for(const q of P){\n"
"  if(!(q.n+' '+q.i).toLowerCase().includes(f))continue;\n"
"  const sec=q.s>=0&&q.s<SECT.length?SECT[q.s]:'';\n"
"  h+=row(q,sec?(sec+(q.g?' · '+q.g:'')):'');\n"
" }\n"
" h+='</table>';\n"
" $('sections').innerHTML=h||'<p>Ничего не найдено.</p>';\n"
" $('tabs').innerHTML='';$('subtabs').innerHTML='';\n"
"}\n"
"function go(k){cur=k;render(built);syncPw();applyFilter()}\n"
"function go2(k){curT[cur]=k;applyFilter()}\n"
"function go3(k){curS[cur+'|'+curTab]=k;applyFilter()}\n"
"function applyFilter(){\n"
" const f=$('filter').value.trim().toLowerCase();\n"
" if(!f){render(built);return}\n"
" renderSearch(f);\n"
"}\n"
"function curVal(q){\n"
" const i=q.i,g=x=>$(x+i);\n"
" if(q.t===10||q.t===11)return g('w').value;\n"
" if(q.t===2)return p2(g('wh').value)+':'+p2(g('wm').value);\n"
" if(q.t===3)return p2(g('wd').value)+'.'+p2(g('wm2').value)+'.'+p2(g('wy').value);\n"
" return g('w').value;\n"
"}\n"
"function flash(msg){\n"
" $('applyMsg').textContent=msg;\n"
" setTimeout(()=>{if($('applyMsg').textContent===msg)$('applyMsg').textContent=''},2500);\n"
"}\n"
"/* apply every edited parameter, unlocking its menu with the section\n"
" * password first; the first failure aborts the rest */\n"
"async function applyAll(){\n"
" const ids=[...dirty];\n"
" if(!ids.length){flash('нет изменений');return}\n"
" $('btnApply').disabled=true;\n"
" let done=0;\n"
" for(const i of ids){\n"
"  const q=P.find(x=>x.i===i);\n"
"  if(!q)continue;\n"
"  const body='id='+i+'&v='+encodeURIComponent(curVal(q))+'&pw='+encodeURIComponent(pwMap[q.s]||'');\n"
"  try{\n"
"   const r=await (await fetch('/api/set',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body})).json();\n"
"   if(!r.ok){alert('«'+(q.n||('P'+i))+'»: '+r.error);break}\n"
"   dirty.delete(i);done++;\n"
"   unmark(i);\n"
"   if(q.m){const w=$('w'+i);if(w)w.value=''}\n"
"  }catch(e){alert('нет ответа от шлюза');break}\n"
" }\n"
" $('btnApply').disabled=false;\n"
" if(done)flash('применено: '+done);\n"
"}\n"
"/* run a menu command item ('x'), unlocked with its section password */\n"
"async function runParam(i){\n"
" const q=P.find(x=>x.i===i);\n"
" if(!q||!q.cx)return;\n"
" if(!confirm('Выполнить «'+(q.n||('P'+i))+'»?'))return;\n"
" try{\n"
"  const r=await (await fetch('/api/run',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},\n"
"   body:'id='+i+'&pw='+encodeURIComponent(pwMap[q.s]||'')})).json();\n"
"  if(!r.ok)alert('«'+(q.n||('P'+i))+'»: '+r.error);\n"
"  else flash('команда выполнена');\n"
" }catch(e){alert('нет ответа от шлюза')}\n"
"}\n"
"/* \"Обновить\": full 'l' listing on the device (settings poll is on-demand\n"
" * only), then the page reloads from the refreshed cache */\n"
"async function refreshAll(){\n"
" if(dirty.size&&!confirm('Есть несохранённые изменения. Обновить без применения?'))return;\n"
" const b=$('btnRefresh');b.disabled=true;b.textContent='Обновление…';\n"
" try{\n"
"  const r=await (await fetch('/api/refresh',{method:'POST'})).json();\n"
"  if(!r.ok)alert('Прибор не ответил на запрос листинга');\n"
"  await tick();\n"
" }catch(e){alert('нет ответа от шлюза')}\n"
" b.disabled=false;b.textContent='Обновить';\n"
"}\n"
"async function rescan(){await fetch('/api/rescan',{method:'POST'});built='';tick()}\n"
"function rebootDev(){if(confirm('Перезагрузить прибор?'))fetch('/api/reboot',{method:'POST'})}\n"
"tick();\n"
"</script></body></html>\n";

#endif /* GW_PAGES_H */
